import PaperC.Combinatorics.GraphCycleRank
import PaperC.Affine.StartSystem
import Mathlib.LinearAlgebra.Matrix.Rank
import Mathlib.Logic.Relation

/-! # The cycle dimension of every finite graph

Edges are an arbitrary finite endpoint presentation, allowing repeated edges
and loops. Components are computed as the equivalence closure of the actual
edges. The kernel of the transpose incidence consists precisely of functions
constant on those components; rank-nullity proves the cyclomatic formula.
-/
namespace PaperC.V282.ClosureAlgebraIncidence

open GraphCycleRank Matrix Module
open scoped BigOperators

noncomputable section

local instance instPrimeTwo : Fact (Nat.Prime 2) := Fact.mk Nat.prime_two

variable {V E : Type*} [Fintype V] [Fintype E] [DecidableEq V] [DecidableEq E]

/-- Connectivity generated by the edges, with no supplied component summary. -/
def componentSetoid (left right : E → V) : Setoid V :=
  Relation.EqvGen.setoid (fun v w => ∃ e, left e = v ∧ right e = w)

/-- The genuine finite component type of an endpoint presentation. -/
def Component (left right : E → V) := Quotient (componentSetoid left right)

instance instFiniteComponent (left right : E → V) : Finite (Component left right) :=
  inferInstanceAs (Finite (Quotient (componentSetoid left right)))

instance instFintypeComponent (left right : E → V) : Fintype (Component left right) :=
  Fintype.ofFinite _

/-- The component containing a vertex. -/
def component (left right : E → V) (v : V) : Component left right := Quotient.mk _ v

omit [Fintype V] [Fintype E] [DecidableEq V] [DecidableEq E] in
theorem component_surjective (left right : E → V) : Function.Surjective (component left right) :=
  Quotient.mk_surjective

omit [Fintype V] [Fintype E] [DecidableEq V] [DecidableEq E] in
theorem component_edge (left right : E → V) (e : E) :
    component left right (left e) = component left right (right e) :=
  Quotient.sound (Relation.EqvGen.rel _ _ ⟨e,rfl,rfl⟩)

/-- The transpose incidence reads the binary difference along each edge. -/
def gradientMatrix (left right : E → V) : Matrix E V F₂ :=
  fun e v => (if v = left e then 1 else 0) + (if v = right e then 1 else 0)

omit [Fintype E] [DecidableEq E] in
theorem gradientMatrix_apply (left right : E → V) (z : V → F₂) (e : E) :
    (gradientMatrix left right).mulVecLin z e = z (left e) + z (right e) := by
  simp [gradientMatrix, Matrix.mulVec, dotProduct, add_mul, Finset.sum_add_distrib]

omit [Fintype E] [DecidableEq E] in
theorem mem_gradient_kernel_iff (left right : E → V) (z : V → F₂) :
    z ∈ LinearMap.ker (gradientMatrix left right).mulVecLin ↔
      ∀ e, z (left e) = z (right e) := by
  simp only [LinearMap.mem_ker, funext_iff, Pi.zero_apply, gradientMatrix_apply,
    Affine.add_eq_zero_iff_eq]

omit [Fintype V] [Fintype E] [DecidableEq V] [DecidableEq E] in
/-- Edgewise equality propagates along the full equivalence closure. -/
theorem constant_on_component (left right : E → V) (z : V → F₂)
    (hz : ∀ e, z (left e) = z (right e)) {v w : V}
    (h : component left right v = component left right w) : z v = z w := by
  have heq : Relation.EqvGen (fun v w => ∃ e, left e = v ∧ right e = w) v w :=
    Quotient.exact h
  clear h
  induction heq with
  | rel v w he => obtain ⟨e,rfl,rfl⟩ := he; exact hz e
  | refl v => rfl
  | symm v w _ ih => exact ih.symm
  | trans v w u _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- Pullback of functions on actual components. -/
def componentFunctions (left right : E → V) :
    (Component left right → F₂) →ₗ[F₂] (V → F₂) where
  toFun f v := f (component left right v)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

omit [Fintype V] [Fintype E] [DecidableEq V] [DecidableEq E] in
theorem componentFunctions_injective (left right : E → V) :
    Function.Injective (componentFunctions left right) := by
  intro f g h
  funext c
  obtain ⟨v,rfl⟩ := component_surjective left right c
  exact congrFun h v

omit [Fintype E] [DecidableEq E] in
/-- The transpose kernel has exactly one free bit per connected component. -/
theorem range_componentFunctions (left right : E → V) :
    LinearMap.range (componentFunctions left right) =
      LinearMap.ker (gradientMatrix left right).mulVecLin := by
  ext z
  constructor
  · rintro ⟨f,rfl⟩
    rw [mem_gradient_kernel_iff]
    intro e
    change f (component left right (left e)) = f (component left right (right e))
    rw [component_edge]
  · intro hz
    have hh := (mem_gradient_kernel_iff left right z).mp hz
    let f : Component left right → F₂ := Quotient.lift z (fun v w h =>
      constant_on_component left right z hh (Quotient.sound h))
    exact ⟨f,rfl⟩

omit [Fintype E] [DecidableEq E] in
theorem finrank_gradient_kernel (left right : E → V) :
    finrank F₂ (LinearMap.ker (gradientMatrix left right).mulVecLin) =
      Fintype.card (Component left right) := by
  rw [← range_componentFunctions, LinearMap.finrank_range_of_inj
    (componentFunctions_injective left right)]
  exact Module.finrank_fintype_fun_eq_card F₂

/-- Identification with the historical binary incidence map. -/
theorem transpose_gradient_eq_incidence (left right : E → V) :
    (gradientMatrix left right).transpose.mulVecLin = incidenceMap left right := by
  apply LinearMap.ext
  intro x
  funext v
  simp only [Matrix.mulVecLin_apply, Matrix.mulVec, dotProduct, Matrix.transpose_apply,
    gradientMatrix, incidenceMap_apply]
  apply Finset.sum_congr rfl
  intro e _
  ring

/-- Exact incidence rank, in additive form to avoid truncated subtraction. -/
theorem incidence_rank_add_components (left right : E → V) :
    finrank F₂ (LinearMap.range (incidenceMap left right)) +
      Fintype.card (Component left right) = Fintype.card V := by
  have h := LinearMap.finrank_range_add_finrank_ker (gradientMatrix left right).mulVecLin
  rw [finrank_gradient_kernel, Module.finrank_fintype_fun_eq_card] at h
  have hr : finrank F₂ (LinearMap.range (incidenceMap left right)) =
      finrank F₂ (LinearMap.range (gradientMatrix left right).mulVecLin) := by
    rw [← transpose_gradient_eq_incidence]
    exact Matrix.rank_transpose (gradientMatrix left right)
  rw [hr]
  exact h

/-- The genuine cycle space has dimension |E|+c-|V|, including empty graphs. -/
theorem finrank_cycleSpace (left right : E → V) :
    finrank F₂ (cycleSpace left right) =
      Fintype.card E + Fintype.card (Component left right) - Fintype.card V := by
  have hr := incidence_rank_add_components left right
  have hn := LinearMap.finrank_range_add_finrank_ker (incidenceMap left right)
  rw [Module.finrank_fintype_fun_eq_card] at hn
  change finrank F₂ (LinearMap.ker (incidenceMap left right)) = _
  omega

end
end PaperC.V282.ClosureAlgebraIncidence
