import PaperCV282.CompoundPoissonMarking
import PaperCV282.ExactMarkedTailTarget

/-!
# A genuine countably marked Poisson configuration

Configurations have finite support in the excess mark. They are generated by
an actual Poisson number of independent positive geometric marks. Every finite
projection is identified with its independent product Poisson law.
-/

namespace PaperC.V282.GeometricMarkedConfiguration

open MeasureTheory ProbabilityTheory CompoundPoissonTarget CompoundPoissonMarking
open GeometricClusterTarget GeometricClusterTruncation PoissonFieldMeasure
open scoped BigOperators NNReal ENNReal

noncomputable section

instance instMeasurableClusterConfiguration : MeasurableSpace (ℕ →₀ ℕ) := ⊤

instance instMeasurableSingletonClusterConfiguration : MeasurableSingletonClass (ℕ →₀ ℕ) := by
  infer_instance

def clusterConfiguration (sample : ℕ × (ℕ → ℕ)) : ℕ →₀ ℕ :=
  ∑ i ∈ Finset.range sample.1,
    if 0 < sample.2 i then Finsupp.single (sample.2 i - 1) 1 else 0

theorem measurable_clusterConfiguration : Measurable clusterConfiguration := by
  apply measurable_from_prod_countable_right
  intro n
  change Measurable (fun marks : ℕ → ℕ => ∑ i ∈ Finset.range n,
    if 0 < marks i then Finsupp.single (marks i - 1) 1 else 0)
  exact Finset.measurable_sum _ (fun i _ =>
    (measurable_of_countable (fun h : ℕ =>
      if 0 < h then (Finsupp.single (h - 1) 1 : ℕ →₀ ℕ) else 0)).comp
        (measurable_pi_apply i))

theorem clusterConfiguration_apply (sample : ℕ × (ℕ → ℕ)) (e : ℕ) :
    clusterConfiguration sample e =
      ∑ i ∈ Finset.range sample.1, if sample.2 i = e + 1 then 1 else 0 := by
  classical
  simp only [clusterConfiguration, Finsupp.finsetSum_apply]
  apply Finset.sum_congr rfl
  intro i hi
  by_cases hp : 0 < sample.2 i
  · have heq : sample.2 i - 1 = e ↔ sample.2 i = e + 1 := by omega
    simp [hp, Finsupp.single_apply, heq]
  · have hzero : sample.2 i = 0 := by omega
    simp [hzero]

def excessCategory (E h : ℕ) : Option (Fin (E + 1)) :=
  if hh : 1 ≤ h ∧ h ≤ E + 1 then some ⟨h - 1, by omega⟩ else none

theorem excessCategory_eq_some_iff (E h : ℕ) (e : Fin (E + 1)) :
    excessCategory E h = some e ↔ h = e.val + 1 := by
  unfold excessCategory
  split_ifs with hh
  · simp only [Option.some.injEq]
    constructor
    · intro he
      have := congrArg Fin.val he
      simp only at this
      omega
    · intro he
      apply Fin.ext
      simp [he]
  · simp only [false_iff]
    intro he
    apply hh
    constructor <;> omega

theorem categoryCounts_excess_eq (E : ℕ) :
    categoryCounts (excessCategory E) =
      fun sample e => clusterConfiguration sample e.val := by
  funext sample e
  simp only [categoryCounts, clusterConfiguration_apply, excessCategory_eq_some_iff]

theorem categoryRates_excess_eq (rate : ℝ≥0) (E : ℕ) :
    categoryRates rate geometricClusterMeasure (excessCategory E) = geometricCoordinateRates rate E := by
  funext e
  apply NNReal.coe_injective
  rw [categoryRates_coe]
  have heq : {h : ℕ | excessCategory E h = some e} = {e.val + 1} := by
    ext h
    exact excessCategory_eq_some_iff E h e
  rw [heq, geometricClusterMeasure_real_succ]
  simp [geometricCoordinateRates, div_eq_mul_inv]

def configurationMeasure (rate : ℝ≥0) : Measure (ℕ →₀ ℕ) :=
  (compoundSampleMeasure rate geometricClusterMeasure).map clusterConfiguration

instance instProbabilityConfiguration (rate : ℝ≥0) : IsProbabilityMeasure (configurationMeasure rate) :=
  Measure.isProbabilityMeasure_map measurable_clusterConfiguration.aemeasurable

theorem hasLaw_configuration (rate : ℝ≥0) :
    HasLaw clusterConfiguration (configurationMeasure rate)
      (compoundSampleMeasure rate geometricClusterMeasure) :=
  ⟨measurable_clusterConfiguration.aemeasurable, rfl⟩

/-- Each finite projection has all its independent Poisson coordinates with exact rates. -/
theorem hasLaw_finite_configuration (rate : ℝ≥0) (E : ℕ) :
    HasLaw (fun config : ℕ →₀ ℕ => fun e : Fin (E + 1) => config e.val)
      (fieldMeasure (geometricCoordinateRates rate E)) (configurationMeasure rate) := by
  have h := hasLaw_categoryCounts rate geometricClusterMeasure (excessCategory E)
  rw [categoryCounts_excess_eq, categoryRates_excess_eq] at h
  refine ⟨(measurable_of_countable _).aemeasurable, ?_⟩
  rw [configurationMeasure, Measure.map_map (measurable_of_countable _) measurable_clusterConfiguration]
  exact h.map_eq

def configurationWeight (config : ℕ →₀ ℕ) : ℕ :=
  config.sum (fun e n => (e + 1) * n)

theorem configurationWeight_clusterConfiguration (sample : ℕ × (ℕ → ℕ)) :
    configurationWeight (clusterConfiguration sample) = stoppedMarkSum sample := by
  classical
  unfold configurationWeight clusterConfiguration stoppedMarkSum
  rw [← Finsupp.sum_finsetSum_index]
  · apply Finset.sum_congr rfl
    intro i hi
    by_cases hpos : 0 < sample.2 i
    · rw [if_pos hpos, Finsupp.sum_single_index (by simp)]
      simp only [mul_one]
      omega
    · rw [if_neg hpos, Finsupp.sum_zero_index]
      omega
  · intro e
    simp
  · intro e n m
    exact Nat.mul_add _ _ _

/-- The unbounded configuration weight is exactly the independent geometric compound law. -/
theorem hasLaw_configurationWeight (rate : ℝ≥0) :
    HasLaw configurationWeight (geometricCompoundMeasure rate) (configurationMeasure rate) := by
  refine ⟨(measurable_of_countable _).aemeasurable, ?_⟩
  rw [configurationMeasure, Measure.map_map (measurable_of_countable _) measurable_clusterConfiguration]
  have heq : configurationWeight ∘ clusterConfiguration = stoppedMarkSum :=
    funext configurationWeight_clusterConfiguration
  rw [heq]
  exact (hasLaw_geometric_random_sum rate).map_eq

end
end PaperC.V282.GeometricMarkedConfiguration
