import PaperCV282.InfiniteWordTransfer

/-!
# Prescribed words on small-prime atoms in the infinite model

The small-prime restriction defines a finite measurable partition. Every
assignment has positive source measure. On a good window, each atom has
exact word probability `2⁻ᴮ`. These are literal intersection and ratio
identities; no general conditional-expectation kernel is asserted here.
-/

namespace PaperC.V282.InfiniteConditionalWords

open MeasureTheory Set
open Affine ConditionalStartProbability InfiniteRademacher InfiniteCylinderTransfer
open InfiniteExactLengthProbabilityTransfer
open PrescribedValues WindowValues InfiniteWordTransfer
open scoped ENNReal

local instance instMeasurableSpaceF2Discrete : MeasurableSpace F₂ := ⊤

noncomputable section

/-- The small-prime coordinates of an infinite sample, represented at cutoff `M`. -/
def smallPrimeRestriction (M Y : ℕ) (ω : InfiniteSample) : SmallSample M Y :=
  restrictSmall M Y (restrictToFinite M ω)

/-- The infinite event fixing one assignment on the represented small primes. -/
def infiniteSmallPrimeAtom (M Y : ℕ) (σ : SmallSample M Y) : Set InfiniteSample :=
  {ω | smallPrimeRestriction M Y ω = σ}

/-- The finite-cylinder event fixing the same small-prime assignment. -/
def finiteSmallPrimeAtom (M Y : ℕ) (σ : SmallSample M Y) : Set (SampleSpace M) :=
  {ω | restrictSmall M Y ω = σ}

/-- The small-prime restriction consists of measurable coordinate evaluations. -/
theorem measurable_smallPrimeRestriction (M Y : ℕ) :
    Measurable (smallPrimeRestriction M Y) := by
  exact measurable_pi_lambda _ fun p ↦ measurable_pi_apply (finitePrimeCoordinate M p.1)

/-- The source atom is exactly the preimage of the finite-cylinder atom. -/
theorem infiniteSmallPrimeAtom_eq_preimage (M Y : ℕ) (σ : SmallSample M Y) :
    infiniteSmallPrimeAtom M Y σ = restrictToFinite M ⁻¹' finiteSmallPrimeAtom M Y σ := rfl

/-- Each small-prime assignment event is measurable in the source model. -/
theorem measurableSet_infiniteSmallPrimeAtom (M Y : ℕ) (σ : SmallSample M Y) :
    MeasurableSet (infiniteSmallPrimeAtom M Y σ) := by
  exact (measurable_smallPrimeRestriction M Y) (measurableSet_singleton σ)

/-- An adequate cutoff represents exactly the primes at most `Y`. -/
def smallPrimeCoordinateEquiv {M Y : ℕ} (hYM : Y ≤ M) :
    SmallPrimeCoordinate M Y ≃ PrimeUpTo Y where
  toFun p := ⟨⟨p.1.1.1, Nat.lt_succ_of_le p.2⟩, p.1.2⟩
  invFun p := ⟨⟨⟨p.1.1, by have hp := p.1.2; omega⟩, p.2⟩,
    Nat.le_of_lt_succ p.1.2⟩
  left_inv p := by
    apply Subtype.ext
    apply Subtype.ext
    apply Fin.ext
    rfl
  right_inv p := by
    apply Subtype.ext
    apply Fin.ext
    rfl

/-- With `Y ≤ M`, an atom fixes all prime signs at most `Y`, with none missing. -/
theorem mem_infiniteSmallPrimeAtom_iff {M Y : ℕ} (hYM : Y ≤ M)
    (σ : SmallSample M Y) (ω : InfiniteSample) :
    ω ∈ infiniteSmallPrimeAtom M Y σ ↔
      ∀ p : PrimeUpTo Y, restrictToFinite Y ω p = σ ((smallPrimeCoordinateEquiv hYM).symm p) := by
  constructor
  · intro h p
    exact congrFun h ((smallPrimeCoordinateEquiv hYM).symm p)
  · intro h
    change smallPrimeRestriction M Y ω = σ
    funext p
    exact h (smallPrimeCoordinateEquiv hYM p)

/-- The sigma-algebra generated by the represented small-prime restriction. -/
@[reducible]
def smallPrimeSigmaAlgebra (M Y : ℕ) : MeasurableSpace InfiniteSample :=
  MeasurableSpace.comap (smallPrimeRestriction M Y) inferInstance

/-- The small-prime sigma-algebra is a sub-sigma-algebra of the source space. -/
theorem smallPrimeSigmaAlgebra_le (M Y : ℕ) :
    smallPrimeSigmaAlgebra M Y ≤ (inferInstance : MeasurableSpace InfiniteSample) :=
  (measurable_smallPrimeRestriction M Y).comap_le

/-- The conditioning atoms belong to the sigma-algebra of the small primes. -/
theorem measurableSet_atom_smallPrimeSigmaAlgebra (M Y : ℕ) (σ : SmallSample M Y) :
    MeasurableSet[smallPrimeSigmaAlgebra M Y] (infiniteSmallPrimeAtom M Y σ) :=
  (comap_measurable (smallPrimeRestriction M Y)) (measurableSet_singleton σ)

/-- With an adequate cutoff this is precisely the sigma-algebra of all primes `≤ Y`. -/
theorem smallPrimeSigmaAlgebra_eq_primeCylinder {M Y : ℕ} (hYM : Y ≤ M) :
    smallPrimeSigmaAlgebra M Y =
      MeasurableSpace.comap (restrictToFinite Y) inferInstance := by
  apply le_antisymm
  · exact MeasurableSpace.comap_le_comap_of_eq_comp
      (fun (τ : SampleSpace Y) p => τ (smallPrimeCoordinateEquiv hYM p))
      (measurable_of_finite _) rfl
  · exact MeasurableSpace.comap_le_comap_of_eq_comp
      (fun (σ : SmallSample M Y) p => σ ((smallPrimeCoordinateEquiv hYM).symm p))
      (measurable_of_finite _) rfl

/-- Completing a fixed assignment also identifies the corresponding event fibers. -/
def completionEventEquiv (M Y : ℕ) (σ : SmallSample M Y) (P : SampleSpace M → Prop) :
    {η : LargeSample M Y // P (assemble M Y σ η)} ≃
      {ω : SampleSpace M // P ω ∧ restrictSmall M Y ω = σ} where
  toFun η := ⟨(completionEquiv M Y σ η.1).1, η.2,
    (completionEquiv M Y σ η.1).2⟩
  invFun ω := ⟨(completionEquiv M Y σ).symm ⟨ω.1, ω.2.2⟩, by
    have h := congrArg Subtype.val
      ((completionEquiv M Y σ).apply_symm_apply ⟨ω.1, ω.2.2⟩)
    change P ((completionEquiv M Y σ) _).1
    rw [h]
    exact ω.2.1⟩
  left_inv η := by
    apply Subtype.ext
    exact (completionEquiv M Y σ).symm_apply_apply η.1
  right_inv ω := by
    apply Subtype.ext
    simpa only using congrArg Subtype.val
      ((completionEquiv M Y σ).apply_symm_apply ⟨ω.1, ω.2.2⟩)

/-- Generic uniform finite event probability as a ratio of subtype cardinalities. -/
theorem uniformEventProbability_eq_card (M : ℕ) (P : SampleSpace M → Prop)
    [DecidablePred P] :
    uniformEventProbability P =
      (Fintype.card {ω : SampleSpace M // P ω} : ℚ) / Fintype.card (SampleSpace M) := by
  simp only [uniformEventProbability, Fintype.card_subtype]

/-- The exact positive mass of every small-prime atom. -/
theorem infiniteSmallPrimeAtom_measure (M Y : ℕ) (σ : SmallSample M Y) :
    infiniteRademacherMeasure (infiniteSmallPrimeAtom M Y σ) =
      ENNReal.ofReal
        (((Fintype.card (LargeSample M Y) : ℚ) / Fintype.card (SampleSpace M) : ℚ) : ℝ) := by
  classical
  rw [infiniteSmallPrimeAtom_eq_preimage,
    ← Measure.map_apply (measurable_restrictToFinite M)
      (Set.toFinite (finiteSmallPrimeAtom M Y σ) |>.measurableSet),
    map_infiniteRademacherMeasure_restrictToFinite]
  change finiteRademacherMeasure M {ω | restrictSmall M Y ω = σ} = _
  rw [finiteRademacherMeasure_event_eq_uniformEventProbability,
    uniformEventProbability_eq_card,
    ← Fintype.card_congr (completionEquiv M Y σ)]

/-- No small-prime assignment is a null conditioning event. -/
theorem infiniteSmallPrimeAtom_measure_pos (M Y : ℕ) (σ : SmallSample M Y) :
    0 < infiniteRademacherMeasure (infiniteSmallPrimeAtom M Y σ) := by
  rw [infiniteSmallPrimeAtom_measure]
  apply ENNReal.ofReal_pos.mpr
  exact_mod_cast (div_pos
    (show (0 : ℚ) < Fintype.card (LargeSample M Y) by exact_mod_cast Fintype.card_pos)
    (show (0 : ℚ) < Fintype.card (SampleSpace M) by exact_mod_cast Fintype.card_pos))

/-- Every atom has finite measure. -/
theorem infiniteSmallPrimeAtom_measure_ne_top (M Y : ℕ) (σ : SmallSample M Y) :
    infiniteRademacherMeasure (infiniteSmallPrimeAtom M Y σ) ≠ ⊤ := by
  rw [infiniteSmallPrimeAtom_measure]
  exact ENNReal.ofReal_ne_top

/-- Finite joint word/atom probability factors as atom mass times affine fiber probability. -/
theorem finite_word_atom_probability (M Y x B : ℕ)
    (b : Fin B → F₂) (σ : SmallSample M Y) :
    uniformEventProbability
      (fun ω : SampleSpace M => valueSystem M (vertex x B) ω = b ∧
        restrictSmall M Y ω = σ) =
      ((Fintype.card (LargeSample M Y) : ℚ) / Fintype.card (SampleSpace M)) *
        uniformSolutionProbability (largeValueSystem M Y (vertex x B))
          (conditionedValueRhs M Y (vertex x B) b σ) := by
  classical
  rw [uniformEventProbability_eq_card,
    ← Fintype.card_congr (completionEventEquiv M Y σ
      (fun ω => valueSystem M (vertex x B) ω = b))]
  have hcard : Fintype.card {η : LargeSample M Y //
      valueSystem M (vertex x B) (assemble M Y σ η) = b} =
      Fintype.card (Solution (largeValueSystem M Y (vertex x B))
        (conditionedValueRhs M Y (vertex x B) b σ)) := by
    apply Fintype.card_congr
    exact Equiv.subtypeEquivRight (fun η => assemble_solves_values_iff M Y (vertex x B) b σ η)
  rw [hcard, uniformSolutionProbability]
  have hlarge : (Fintype.card (LargeSample M Y) : ℚ) ≠ 0 := by
    exact_mod_cast Fintype.card_ne_zero
  field_simp
  congr 2
  exact Subsingleton.elim _ _

/-- The infinite joint event is the preimage of the finite joint affine event. -/
theorem infinite_word_atom_eq_preimage {M Y x B : ℕ}
    (hcut : x - 1 + B ≤ M + 1) (b : Fin B → F₂) (σ : SmallSample M Y) :
    infiniteWordEvent x B b ∩ infiniteSmallPrimeAtom M Y σ =
      restrictToFinite M ⁻¹' {ω : SampleSpace M |
        valueSystem M (vertex x B) ω = b ∧ restrictSmall M Y ω = σ} := by
  rw [infiniteWordEvent_eq_preimage hcut b, infiniteSmallPrimeAtom_eq_preimage]
  ext ω
  simp only [Set.mem_inter_iff, Set.mem_preimage, finiteWordEvent,
    finiteSmallPrimeAtom, Set.mem_setOf_eq, valueSystem_eq_iff]

/-- Under the odd-valuation good-window hypothesis, each source atom has the
same exact word fraction. The condition `Y ≤ M` gives the full small-prime scope. -/
theorem corollary_two_six_joint_infinite {M Y x B : ℕ}
    (hx : 2 ≤ x) (hcut : x - 1 + B ≤ M + 1) (_hYM : Y ≤ M) (hBY : B ≤ Y)
    (hgood : ∀ i : Fin B, ¬ DefectivePredicate.HDefective Y (vertex x B i))
    (b : Fin B → F₂) (σ : SmallSample M Y) :
    infiniteRademacherMeasure (infiniteWordEvent x B b ∩ infiniteSmallPrimeAtom M Y σ) =
      infiniteRademacherMeasure (infiniteSmallPrimeAtom M Y σ) * (1 / (2 : ℝ≥0∞) ^ B) := by
  classical
  rw [infinite_word_atom_eq_preimage hcut b σ,
    ← Measure.map_apply (measurable_restrictToFinite M)
      (Set.toFinite _ |>.measurableSet),
    map_infiniteRademacherMeasure_restrictToFinite,
    finiteRademacherMeasure_event_eq_uniformEventProbability,
    finite_word_atom_probability,
    WindowValues.corollary_two_six_conditioned hx hcut hBY hgood,
    infiniteSmallPrimeAtom_measure]
  simp only [Rat.cast_mul, Rat.cast_div, Rat.cast_one, Rat.cast_pow, Rat.cast_ofNat]
  rw [ENNReal.ofReal_mul (by positivity)]
  congr 1
  simp [ENNReal.ofReal_pow]

/-- Concrete conditional probability on every small-prime atom is exactly `2⁻ᴮ`. -/
theorem corollary_two_six_conditioned_infinite {M Y x B : ℕ}
    (hx : 2 ≤ x) (hcut : x - 1 + B ≤ M + 1) (hYM : Y ≤ M) (hBY : B ≤ Y)
    (hgood : ∀ i : Fin B, ¬ DefectivePredicate.HDefective Y (vertex x B i))
    (b : Fin B → F₂) (σ : SmallSample M Y) :
    infiniteRademacherMeasure (infiniteWordEvent x B b ∩ infiniteSmallPrimeAtom M Y σ) /
      infiniteRademacherMeasure (infiniteSmallPrimeAtom M Y σ) = 1 / (2 : ℝ≥0∞) ^ B := by
  rw [corollary_two_six_joint_infinite hx hcut hYM hBY hgood b σ, mul_comm]
  exact ENNReal.mul_div_cancel_right
    (ne_of_gt (infiniteSmallPrimeAtom_measure_pos M Y σ))
    (infiniteSmallPrimeAtom_measure_ne_top M Y σ)

end
end PaperC.V282.InfiniteConditionalWords
