import PaperCV282.SharpConditioningDiscrete
import PaperCV282.GeometricConfigurationCounts
import PaperCV282.ThresholdPathEquivalence

/-! # The whole geometric-lifetime target after resolution of its present count -/
namespace PaperC.V282.PoissonResolvedTarget

open MeasureTheory ProbabilityTheory GeometricMarkedConfiguration GeometricConfigurationCounts
open GeometricClusterTarget CompoundPoissonTarget ThresholdPathEquivalence
open SharpConditioningDiscrete ConditionedCountableLaw
open scoped NNReal ENNReal

noncomputable section

@[reducible]
local instance instDecidableProposition (P : Prop) : Decidable P := Classical.propDecidable P

theorem cond_congr_ae {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω)
    {A B : Set Ω} (h : A =ᵐ[μ] B) : cond μ A = cond μ B := by
  rw [ProbabilityTheory.cond, ProbabilityTheory.cond, measure_congr h, Measure.restrict_congr_set h]

theorem cond_prod_first_eq {Ω : Type*} [MeasurableSpace Ω]
    (μ : Measure ℕ) [IsProbabilityMeasure μ] (ν : Measure Ω) [IsProbabilityMeasure ν]
    (n : ℕ) (hn : μ {n} ≠ 0) :
    cond (μ.prod ν) (Prod.fst ⁻¹' {n}) = (Measure.dirac n).prod ν := by
  have hs : (Prod.fst ⁻¹' {n} : Set (ℕ × Ω)) = {n} ×ˢ Set.univ := by ext x; simp
  rw [hs, ProbabilityTheory.cond, Measure.prod_prod, measure_univ, mul_one,
    ← Measure.restrict_prod_eq_prod_univ, Measure.restrict_singleton,
    Measure.prod_smul_left, smul_smul, ENNReal.inv_mul_cancel hn (measure_ne_top μ {n}), one_smul]

def thinConfigurationMeasure (n : ℕ) : Measure (ℕ →₀ ℕ) :=
  (markSequenceMeasure geometricClusterMeasure).map (fun marks => clusterConfiguration (n, marks))

theorem measurable_fixed_configuration (n : ℕ) :
    Measurable (fun marks : ℕ → ℕ => clusterConfiguration (n, marks)) :=
  measurable_clusterConfiguration.comp measurable_prodMk_left

instance instProbabilityThinConfiguration (n : ℕ) : IsProbabilityMeasure (thinConfigurationMeasure n) :=
  Measure.isProbabilityMeasure_map (measurable_fixed_configuration n).aemeasurable

/-- A Poisson configuration conditioned by its entire present count is generated by exactly n iid marks. -/
theorem conditional_configuration_eq_thin (rate : ℝ≥0) (n : ℕ)
    (hn : (poissonMeasure rate) {n} ≠ 0) :
    cond (configurationMeasure rate) {c | configurationSize c = n} = thinConfigurationMeasure n := by
  have hae : clusterConfiguration ⁻¹' {c | configurationSize c = n} =ᵐ[
      compoundSampleMeasure rate geometricClusterMeasure] (Prod.fst ⁻¹' {n}) := by
    filter_upwards [configurationSize_eq_count_ae rate] with sample hs
    change (configurationSize (clusterConfiguration sample) = n) = (sample.1 = n)
    rw [hs]
  rw [configurationMeasure, ← map_cond_eq _ measurable_clusterConfiguration _
    ((Set.to_countable _).measurableSet), cond_congr_ae _ hae]
  rw [compoundSampleMeasure, cond_prod_first_eq _ _ n hn, Measure.dirac_prod,
    Measure.map_map measurable_clusterConfiguration measurable_prodMk_left]
  rfl

def lifetimePath (n : ℕ) (marks : ℕ → ℕ) (j : ℕ) : ℕ :=
  ∑ i ∈ Finset.range n, if j < marks i then 1 else 0

theorem measurable_lifetimePath (n : ℕ) : Measurable (lifetimePath n) := by
  apply measurable_pi_lambda
  intro j
  exact Finset.measurable_sum _ (fun i _ =>
    (measurable_of_countable (fun h : ℕ => if j < h then 1 else 0)).comp (measurable_pi_apply i))

theorem threshold_fixed_configuration (n : ℕ) (marks : ℕ → ℕ) :
    thresholdFunction (clusterConfiguration (n, marks)) = lifetimePath n marks := by
  classical
  funext j
  change (clusterConfiguration (n, marks)).sum (fun e a => if j ≤ e then a else 0) = _
  unfold clusterConfiguration
  rw [← Finsupp.sum_finsetSum_index]
  · apply Finset.sum_congr rfl
    intro i hi
    by_cases hp : 0 < marks i
    · rw [if_pos hp, Finsupp.sum_single_index (by simp)]
      have he : j ≤ marks i - 1 ↔ j < marks i := by omega
      simp [he]
    · rw [if_neg hp, Finsupp.sum_zero_index]
      simp [show ¬ j < marks i by omega]
  · intro e
    simp
  · intro e a b
    split_ifs <;> simp

/-- The complete future path of n independent geometric lifetimes. -/
def thinningPathMeasure (n : ℕ) : Measure (ℕ → ℕ) :=
  (markSequenceMeasure geometricClusterMeasure).map (lifetimePath n)

instance instProbabilityThinningPath (n : ℕ) : IsProbabilityMeasure (thinningPathMeasure n) :=
  Measure.isProbabilityMeasure_map (measurable_lifetimePath n).aemeasurable

theorem thinConfiguration_path (n : ℕ) :
    (thinConfigurationMeasure n).map thresholdFunction = thinningPathMeasure n := by
  rw [thinConfigurationMeasure, Measure.map_map (measurable_of_countable _)
    (measurable_fixed_configuration n)]
  congr 1
  funext marks
  exact threshold_fixed_configuration n marks

/-- Whole-path identity, rather than just the individual binomial marginals. -/
theorem conditional_future_path_eq (rate : ℝ≥0) (n : ℕ)
    (hn : (poissonMeasure rate) {n} ≠ 0) :
    (cond (configurationMeasure rate) {c | configurationSize c = n}).map thresholdFunction =
      thinningPathMeasure n := by
  rw [conditional_configuration_eq_thin rate n hn, thinConfiguration_path]

/-- The resolution probability is the actual, explicit Poisson atom. -/
theorem configuration_size_probability (rate : ℝ≥0) (n : ℕ) :
    (configurationMeasure rate).real {c | configurationSize c = n} =
      Real.exp (-(rate : ℝ)) * (rate : ℝ) ^ n / n.factorial := by
  have h := (hasLaw_configurationSize rate).measureReal_eq (measurableSet_singleton n)
  exact h.trans (poissonMeasure_real_singleton rate n)

theorem configuration_size_probability_pos (rate : ℝ≥0) (hr : 0 < rate) (n : ℕ) :
    0 < (configurationMeasure rate).real {c | configurationSize c = n} := by
  rw [configuration_size_probability]
  positivity

end
end PaperC.V282.PoissonResolvedTarget
