import PaperCV282.PointMeasureSpace
import PaperCV282.GeneralPoissonMarking
import Mathlib.Analysis.Normed.Group.Tannery
import Mathlib.MeasureTheory.Integral.DominatedConvergence

/-! # Actual Poisson point process laws and convergence by coupled marks

The law is generated by an independent Poisson count and iid marks, then
mapped to the finite sum of Dirac measures. The convergence theorem concerns
the weak topology on probability measures, including a varying intensity.
-/
namespace PaperC.V282.PoissonPointProcess

open MeasureTheory ProbabilityTheory Filter PointMeasureSpace GeneralPoissonMarking
open scoped BigOperators Topology NNReal BoundedContinuousFunction

noncomputable section

variable {X Y : Type*} [MeasurableSpace X] [MeasurableSpace Y]
  [TopologicalSpace Y] [BorelSpace Y] [SecondCountableTopology Y]

def mappedPointMeasure (f : X → Y) (sample : ℕ × (ℕ → X)) : PointMeasure Y :=
  samplePointMeasure (sample.1, fun i => f (sample.2 i))

theorem measurable_mappedPointMeasure {f : X → Y} (hf : Measurable f) :
    Measurable (mappedPointMeasure f) := by
  apply measurable_samplePointMeasure.comp
  exact measurable_fst.prodMk (measurable_pi_lambda _ (fun i =>
    hf.comp ((measurable_pi_apply i).comp measurable_snd)))

def poissonPointLaw (rate : ℝ≥0) (mu : Measure X) [IsProbabilityMeasure mu]
    (f : X → Y) (hf : Measurable f) : ProbabilityMeasure (PointMeasure Y) :=
  ⟨(markSampleMeasure rate mu).map (mappedPointMeasure f),
    Measure.isProbabilityMeasure_map (measurable_mappedPointMeasure hf).aemeasurable⟩

theorem hasLaw_mappedPointMeasure (rate : ℝ≥0) (mu : Measure X) [IsProbabilityMeasure mu]
    (f : X → Y) (hf : Measurable f) :
    HasLaw (mappedPointMeasure f) (poissonPointLaw rate mu f hf) (markSampleMeasure rate mu) :=
  ⟨(measurable_mappedPointMeasure hf).aemeasurable, rfl⟩

theorem integral_poissonPointLaw (rate : ℝ≥0) (mu : Measure X) [IsProbabilityMeasure mu]
    (f : X → Y) (hf : Measurable f) (F : PointMeasure Y →ᵇ ℝ) :
    (∫ c, F c ∂(poissonPointLaw rate mu f hf : Measure (PointMeasure Y))) =
      ∑' k : ℕ, (Real.exp (-(rate : ℝ)) * (rate : ℝ) ^ k / k.factorial) *
        ∫ marks, F (fixedPointMeasure k (fun i => f (marks i))) ∂markSequenceMeasure mu := by
  rw [← (hasLaw_mappedPointMeasure rate mu f hf).integral_comp
    F.continuous.measurable.aestronglyMeasurable]
  have hint : Integrable (fun sample => F (mappedPointMeasure f sample))
      (markSampleMeasure rate mu) := by
    refine ⟨(F.continuous.measurable.comp
      (measurable_mappedPointMeasure hf)).aestronglyMeasurable, ?_⟩
    exact HasFiniteIntegral.of_bounded (Filter.Eventually.of_forall
      (fun sample => F.norm_coe_le_norm _))
  simp only [Function.comp_apply]
  rw [markSampleMeasure, integral_prod _ hint, integral_poissonMeasure]
  rfl

theorem fixed_point_integral_tendsto (mu : Measure X) [IsProbabilityMeasure mu]
    (f : ℕ → X → Y) (g : X → Y) (hf : ∀ n, Measurable (f n))
    (hfg : ∀ x, Tendsto (fun n => f n x) atTop (𝓝 (g x)))
    (F : PointMeasure Y →ᵇ ℝ) (k : ℕ) :
    Tendsto (fun n => ∫ marks, F (fixedPointMeasure k (fun i => f n (marks i)))
      ∂markSequenceMeasure mu) atTop
      (𝓝 (∫ marks, F (fixedPointMeasure k (fun i => g (marks i)))
        ∂markSequenceMeasure mu)) := by
  apply tendsto_integral_of_dominated_convergence (fun _ => ‖F‖)
  · intro n
    exact (F.continuous.measurable.comp ((continuous_fixedPointMeasure k).measurable.comp
      (measurable_pi_lambda _ (fun i => (hf n).comp (measurable_pi_apply i))))).aestronglyMeasurable
  · exact integrable_const _
  · intro n
    exact Filter.Eventually.of_forall (fun marks => F.norm_coe_le_norm _)
  · exact Filter.Eventually.of_forall (fun marks => F.continuous.continuousAt.tendsto.comp
      (samplePointMeasure_tendsto (k,marks) f g (fun i => hfg (marks i))))

theorem poisson_mass_le_factorial_bound {rate : ℝ≥0} {K : ℝ} (hK : (rate : ℝ) ≤ K)
    (k : ℕ) : (Real.exp (-(rate : ℝ)) * (rate : ℝ) ^ k / k.factorial) ≤ K ^ k / k.factorial := by
  apply div_le_div_of_nonneg_right _ (Nat.cast_nonneg _)
  calc
    Real.exp (-(rate : ℝ)) * (rate : ℝ) ^ k ≤ 1 * (rate : ℝ) ^ k :=
      mul_le_mul_of_nonneg_right (Real.exp_le_one_iff.mpr (neg_nonpos.mpr rate.coe_nonneg))
        (pow_nonneg rate.coe_nonneg _)
    _ ≤ K ^ k := by simpa using pow_le_pow_left₀ rate.coe_nonneg hK k

set_option maxHeartbeats 800000 in
/-- Weak convergence of actual finite point process laws under a pointwise
coupling of their iid marks, with converging Poisson intensities. -/
theorem poissonPointLaw_tendsto (mu : Measure X) [IsProbabilityMeasure mu]
    (rates : ℕ → ℝ≥0) (rate : ℝ≥0)
    (hrate : Tendsto (fun n => (rates n : ℝ)) atTop (𝓝 (rate : ℝ)))
    (f : ℕ → X → Y) (g : X → Y) (hf : ∀ n, Measurable (f n)) (hg : Measurable g)
    (hfg : ∀ x, Tendsto (fun n => f n x) atTop (𝓝 (g x))) :
    Tendsto (fun n => poissonPointLaw (rates n) mu (f n) (hf n)) atTop
      (𝓝 (poissonPointLaw rate mu g hg)) := by
  rw [ProbabilityMeasure.tendsto_iff_forall_integral_tendsto]
  intro F
  simp_rw [integral_poissonPointLaw]
  let K : ℝ := (rate : ℝ) + 1
  have hK : 0 ≤ K := by dsimp [K]; positivity
  apply tendsto_tsum_of_dominated_convergence
    ((Real.summable_pow_div_factorial K).mul_right ‖F‖)
  · intro k
    apply Tendsto.mul _ (fixed_point_integral_tendsto mu f g hf hfg F k)
    exact (((Real.continuous_exp.tendsto _).comp hrate.neg).mul (hrate.pow k)).div_const _
  · filter_upwards [hrate.eventually_lt_const (show (rate : ℝ) < K by dsimp [K]; linarith)]
      with n hn
    intro k
    have hi : ‖∫ marks, F (fixedPointMeasure k (fun i => f n (marks i)))
        ∂markSequenceMeasure mu‖ ≤ ‖F‖ := by
      have hb : ∀ᵐ marks : ℕ → X ∂markSequenceMeasure mu,
          ‖F (fixedPointMeasure k (fun i => f n (marks i)))‖ ≤ ‖F‖ :=
        Filter.Eventually.of_forall (fun marks => F.norm_coe_le_norm _)
      simpa only [probReal_univ, mul_one] using
        (norm_integral_le_of_norm_le_const (μ := markSequenceMeasure mu) hb)
    rw [norm_mul, Real.norm_eq_abs, abs_of_nonneg (show 0 ≤ Real.exp (-(rates n : ℝ)) * (rates n : ℝ) ^ k / k.factorial by positivity)]
    exact mul_le_mul (poisson_mass_le_factorial_bound hn.le k) hi (norm_nonneg _)
      (div_nonneg (pow_nonneg hK _) (Nat.cast_nonneg _))

end
end PaperC.V282.PoissonPointProcess
