name = "paper_c_lean"
version = "0.42.0"
defaultTargets = ["PaperC"]

[[lean_lib]]
name = "PaperC"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.19.0"
