name = "paper_c_lean"
version = "0.48.1"
defaultTargets = ["PaperC"]

[[lean_lib]]
name = "PaperC"

[[lean_lib]]
name = "PaperCV11"

[[lean_lib]]
name = "PaperCV282"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"

[[lean_lib]]
name = "ChallengeTransfer"

[[lean_lib]]
name = "SolutionTransfer"

[[lean_lib]]
name = "ChallengeTheoremOneTwo"

[[lean_lib]]
name = "SolutionTheoremOneTwo"

[[lean_lib]]
name = "ChallengeTheoremOneFour"

[[lean_lib]]
name = "SolutionTheoremOneFour"

[[lean_lib]]
name = "ChallengeTheoremSixteenTwo"

[[lean_lib]]
name = "SolutionTheoremSixteenTwo"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.0"
