import PaperC.Combinatorics.ResidualComponentCounts
import PaperC.Combinatorics.OneUnitResidualExceptions

set_option maxHeartbeats 1800000

/-!
# The concrete residual component family

This file supplies the finite family denoted by `C_res` in Lemmas 6.4--6.5.
For a channel containing at least two exact units, it is obtained from the
nontrivial unpinned components by deleting the components generated by the
nondefective exact units.  Below that threshold no component is deleted,
exactly as in the corrected counts of `ResidualComponentCounts`.

The construction is also packaged for the optional canonical reduced
candidate.  Its cardinality is the previously defined corrected component
count, and its members satisfy the hypotheses of `ResidualCertificates`.
-/

namespace PaperC
namespace CanonicalResidualComponents

open Affine
open Affine.CanonicalRationalCode
open Affine.RationalChannelCode
open ExactUnitIsolation
open LargePrimeGraph
open LargePrimeGraphResolution
open PinnedGraphResolution
open ResidualComponentCounts
open ResidualCertificates
open OneUnitResidualExceptions

noncomputable section

noncomputable local instance instDecidableLargePrimeAdj
    (x y L : ℕ) :
    DecidableRel (largePrimeGraph x y L).Adj :=
  Classical.decRel _

/-! ## One explicit primitive channel -/

/--
The connected components generated by the nondefective exact units of one
channel.  The definition itself needs no small-coefficient hypothesis; that
hypothesis is used only to prove that the image consists of distinct
nontrivial components.
-/
noncomputable def exactNondefectiveComponents
    (x y L a b : ℕ) (h : ℤ) :
    Finset (largePrimeGraph x y L).ConnectedComponent := by
  classical
  exact Finset.univ.image fun
    unit : NondefectiveChannelUnit x y L a b h ↦
      (largePrimeGraph x y L).connectedComponentMk
        (Sum.inl unit.1.1.1)

@[simp]
theorem mem_exactNondefectiveComponents
    {x y L a b : ℕ} {h : ℤ}
    {C : (largePrimeGraph x y L).ConnectedComponent} :
    C ∈ exactNondefectiveComponents x y L a b h ↔
      ∃ unit : NondefectiveChannelUnit x y L a b h,
        (largePrimeGraph x y L).connectedComponentMk
            (Sum.inl unit.1.1.1) =
          C := by
  classical
  simp [exactNondefectiveComponents]

/--
The concrete residual family `C_res`.  In the active branch `m ≥ 2`, exact
nondefective components are removed; in the degenerate branch the full
nontrivial family is retained.
-/
noncomputable def residualComponents
    (x y L a b : ℕ) (h : ℤ) :
    Finset (largePrimeGraph x y L).ConnectedComponent := by
  classical
  exact
    if 2 ≤ channelUnitCount L a b h then
      nontrivialUnpinnedComponents
          (largePrimeGraph x y L)
          (pinnedVertices x y L) \
        exactNondefectiveComponents x y L a b h
    else
      nontrivialUnpinnedComponents
        (largePrimeGraph x y L)
        (pinnedVertices x y L)

/-- Every member of `C_res` is a nontrivial unpinned component. -/
theorem isNontrivialUnpinnedComponent_of_mem_residualComponents
    {x y L a b : ℕ} {h : ℤ}
    {C : (largePrimeGraph x y L).ConnectedComponent}
    (hC : C ∈ residualComponents x y L a b h) :
    IsNontrivialUnpinnedComponent
      (largePrimeGraph x y L)
      (pinnedVertices x y L) C := by
  classical
  unfold residualComponents at hC
  split at hC
  · exact
      (mem_nontrivialUnpinnedComponents
        (largePrimeGraph x y L)).mp
        (Finset.mem_sdiff.mp hC).1
  · exact
      (mem_nontrivialUnpinnedComponents
        (largePrimeGraph x y L)).mp hC

/--
Under the hypotheses of the exact-unit isolation theorem, every deleted
component is indeed nontrivial and unpinned.
-/
theorem exactNondefectiveComponents_subset_nontrivial
    {x y L a b : ℕ} {h : ℤ}
    (ha : 0 < a) (hb : 0 < b)
    (hab : a.Coprime b)
    (hx : 2 ≤ x) (hy : 2 ≤ y)
    (hheight : h = (b : ℤ) * y - (a : ℤ) * x)
    (hsmall : Nat.max a b < L + 1) :
    exactNondefectiveComponents x y L a b h ⊆
      nontrivialUnpinnedComponents
        (largePrimeGraph x y L)
        (pinnedVertices x y L) := by
  classical
  intro C hC
  obtain ⟨unit, rfl⟩ :=
    mem_exactNondefectiveComponents.mp hC
  exact
    (nondefectiveUnitComponent
      ha hb hab hx hy hheight hsmall unit).2

/-- The deleted family has exactly `n` components. -/
theorem card_exactNondefectiveComponents
    {x y L a b : ℕ} {h : ℤ}
    (ha : 0 < a) (hb : 0 < b)
    (hab : a.Coprime b)
    (hx : 2 ≤ x) (hy : 2 ≤ y)
    (hheight : h = (b : ℤ) * y - (a : ℤ) * x)
    (hsmall : Nat.max a b < L + 1) :
    (exactNondefectiveComponents x y L a b h).card =
      nondefectiveExactUnitCount x y L a b h := by
  classical
  let f :
      NondefectiveChannelUnit x y L a b h →
        (largePrimeGraph x y L).ConnectedComponent :=
    fun unit ↦
      (largePrimeGraph x y L).connectedComponentMk
        (Sum.inl unit.1.1.1)
  have hf : Function.Injective f := by
    intro unit₁ unit₂ huv
    apply
      nondefectiveUnitComponent_injective
        ha hb hab hx hy hheight hsmall
    apply Subtype.ext
    exact huv
  change (Finset.univ.image f).card =
    Fintype.card (NondefectiveChannelUnit x y L a b h)
  rw [Finset.card_image_of_injective Finset.univ hf,
    Finset.card_univ]

/--
The concrete residual family realizes exactly the corrected component count
`c#`.
-/
theorem card_residualComponents
    {x y L a b : ℕ} {h : ℤ}
    (ha : 0 < a) (hb : 0 < b)
    (hab : a.Coprime b)
    (hx : 2 ≤ x) (hy : 2 ≤ y)
    (hheight : h = (b : ℤ) * y - (a : ℤ) * x) :
    (residualComponents x y L a b h).card =
      residualComponentCount x y L a b h := by
  classical
  by_cases hm : 2 ≤ channelUnitCount L a b h
  · have hmUnits :
        2 ≤ (rationalChannelUnits L a b h).card := by
      simpa [channelUnitCount_eq_card_rationalChannelUnits]
        using hm
    have hsmall : Nat.max a b < L + 1 := by
      have hle : Nat.max a b ≤ L :=
        max_channelCoefficients_le_length
          (L := L) (a := a) (b := b) (h := h)
          ha hb hab hmUnits
      omega
    have hsubset :=
      exactNondefectiveComponents_subset_nontrivial
        ha hb hab hx hy hheight hsmall
    simp only [residualComponents, residualComponentCount, if_pos hm]
    rw [Finset.card_sdiff hsubset,
      card_exactNondefectiveComponents
        ha hb hab hx hy hheight hsmall]
    rfl
  · simp [residualComponents, residualComponentCount, hm,
      nontrivialComponentCount]

/-! ## Exact-cell exclusion and certificate extraction -/

/--
When `m ≥ 2`, every exact channel cell has its left component outside
`C_res`.  A defective left endpoint generates a singleton component; a
nondefective endpoint belongs to the family explicitly removed above.
-/
theorem onChannel_component_not_mem_residualComponents
    {x y L a b : ℕ} {h : ℤ}
    (hx : 1 ≤ x) (hy : 1 ≤ y)
    (hm : 2 ≤ channelUnitCount L a b h)
    (cell : Fin (L + 1) × Fin (L + 1))
    (hcell :
      OnChannel a b h
        (channelVertexOffset cell.1,
          channelVertexOffset cell.2)) :
    (largePrimeGraph x y L).connectedComponentMk
        (Sum.inl cell.1) ∉
      residualComponents x y L a b h := by
  classical
  intro hmem
  have hnontrivial :=
    isNontrivialUnpinnedComponent_of_mem_residualComponents hmem
  let unit : ChannelUnit L a b h :=
    ⟨cell, mem_rationalChannelUnits.mpr hcell⟩
  by_cases hdef :
      IsDefective x y L (Sum.inl unit.1.1)
  · have hisolated :=
      isIsolatedUnpinnedComponent_of_isDefective
        hx hy hdef
    have hisolated' :
        IsIsolatedUnpinnedComponent
          (largePrimeGraph x y L)
          (pinnedVertices x y L)
          ((largePrimeGraph x y L).connectedComponentMk
            (Sum.inl cell.1)) := by
      simpa [unit] using hisolated
    rw [IsNontrivialUnpinnedComponent] at hnontrivial
    rw [IsIsolatedUnpinnedComponent] at hisolated'
    omega
  · have himage :
        (largePrimeGraph x y L).connectedComponentMk
            (Sum.inl unit.1.1) ∈
          exactNondefectiveComponents x y L a b h := by
      rw [mem_exactNondefectiveComponents]
      exact ⟨⟨unit, hdef⟩, rfl⟩
    have houtside :
        (largePrimeGraph x y L).connectedComponentMk
            (Sum.inl unit.1.1) ∉
          exactNondefectiveComponents x y L a b h := by
      have hsdiff :
          (largePrimeGraph x y L).connectedComponentMk
              (Sum.inl unit.1.1) ∈
            nontrivialUnpinnedComponents
                (largePrimeGraph x y L)
                (pinnedVertices x y L) \
              exactNondefectiveComponents x y L a b h := by
        simpa [residualComponents, hm] using hmem
      exact (Finset.mem_sdiff.mp hsdiff).2
    exact houtside himage

/--
The preceding theorem is exactly the exclusion hypothesis expected by
`ResidualCertificates`.
-/
theorem residualCertificates_not_onChannel
    {x y L a b : ℕ} {h : ℤ}
    (hx : 1 ≤ x) (hy : 1 ≤ y)
    (hm : 2 ≤ channelUnitCount L a b h)
    (C : {C // C ∈ residualComponents x y L a b h}) :
    ¬OnChannel a b h
      (canonicalCertificates
        hx hy
        (residualComponents x y L a b h)
        (fun _C hC ↦
          isNontrivialUnpinnedComponent_of_mem_residualComponents hC)
        C).offsetCell := by
  apply canonicalCertificates_not_onChannel_of_excluded
  intro cell hcell
  exact
    onChannel_component_not_mem_residualComponents
      hx hy hm cell hcell

/-! ## Canonical optional-candidate wrapper -/

/-- The canonical residual family attached to `canonicalReducedCandidate?`. -/
noncomputable def canonicalResidualComponents
    (A x y L : ℕ) :
    Finset (largePrimeGraph x y L).ConnectedComponent :=
  match canonicalReducedCandidate?
      x y (L + 1) ((L + 1) ^ A) with
  | none =>
      nontrivialUnpinnedComponents
        (largePrimeGraph x y L)
        (pinnedVertices x y L)
  | some c =>
      residualComponents x y L c.1.1 c.1.2
        (pairChannelError x y c.1.1 c.1.2)

/-- Every canonical residual component is nontrivial and unpinned. -/
theorem isNontrivialUnpinnedComponent_of_mem_canonicalResidualComponents
    {A x y L : ℕ}
    {C : (largePrimeGraph x y L).ConnectedComponent}
    (hC : C ∈ canonicalResidualComponents A x y L) :
    IsNontrivialUnpinnedComponent
      (largePrimeGraph x y L)
      (pinnedVertices x y L) C := by
  classical
  generalize hchoice :
      canonicalReducedCandidate?
        x y (L + 1) ((L + 1) ^ A) = choice
  cases choice with
  | none =>
      exact
        (mem_nontrivialUnpinnedComponents
          (largePrimeGraph x y L)).mp
          (by
            simpa [canonicalResidualComponents, hchoice]
              using hC)
  | some c =>
      apply isNontrivialUnpinnedComponent_of_mem_residualComponents
      simpa [canonicalResidualComponents, hchoice] using hC

/-- The canonical family has cardinality `canonicalResidualComponentCount`. -/
theorem card_canonicalResidualComponents
    {A x y L : ℕ}
    (hx : 2 ≤ x) (hy : 2 ≤ y) :
    (canonicalResidualComponents A x y L).card =
      canonicalResidualComponentCount A x y L := by
  classical
  generalize hchoice :
      canonicalReducedCandidate?
        x y (L + 1) ((L + 1) ^ A) = choice
  cases choice with
  | none =>
      simp [canonicalResidualComponents,
        canonicalResidualComponentCount, hchoice,
        nontrivialComponentCount]
  | some c =>
      have hcard :=
        card_residualComponents
          (x := x) (y := y) (L := L)
          (a := c.1.1) (b := c.1.2)
          (h := pairChannelError x y c.1.1 c.1.2)
          (candidate_fst_pos c)
          (candidate_snd_pos c)
          (candidate_coprime c)
          hx hy rfl
      simpa [canonicalResidualComponents,
        canonicalResidualComponentCount, hchoice]
        using hcard

/--
For a selected canonical channel with `m ≥ 2`, the canonical residual
family satisfies the exact-cell exclusion hypothesis.
-/
theorem canonical_onChannel_component_not_mem_of_choice
    {A x y L : ℕ}
    (hx : 1 ≤ x) (hy : 1 ≤ y)
    (c : ReducedCandidate
      x y (L + 1) ((L + 1) ^ A))
    (hchoice :
      canonicalReducedCandidate?
          x y (L + 1) ((L + 1) ^ A) =
        some c)
    (hm :
      2 ≤ channelUnitCount L c.1.1 c.1.2
        (pairChannelError x y c.1.1 c.1.2))
    (cell : Fin (L + 1) × Fin (L + 1))
    (hcell :
      OnChannel c.1.1 c.1.2
        (pairChannelError x y c.1.1 c.1.2)
        (channelVertexOffset cell.1,
          channelVertexOffset cell.2)) :
    (largePrimeGraph x y L).connectedComponentMk
        (Sum.inl cell.1) ∉
      canonicalResidualComponents A x y L := by
  simpa [canonicalResidualComponents, hchoice] using
    onChannel_component_not_mem_residualComponents
      hx hy hm cell hcell

/-! ## Canonical certificate facade -/

/--
Canonical Lemma 6.5 certificate indexed directly by a member of the
canonical residual family.
-/
noncomputable def canonicalResidualCertificates
    {A x y L : ℕ}
    (hx : 1 ≤ x) (hy : 1 ≤ y)
    (C : {C // C ∈ canonicalResidualComponents A x y L}) :
    ComponentCertificate x y L C.1 :=
  canonicalCertificates
    hx hy
    (canonicalResidualComponents A x y L)
    (fun _C hC ↦
      isNontrivialUnpinnedComponent_of_mem_canonicalResidualComponents hC)
    C

/-- Every selected certificate label is a prime above `L+1`. -/
theorem canonicalResidualCertificates_prime_large
    {A x y L : ℕ}
    (hx : 1 ≤ x) (hy : 1 ≤ y)
    (C : {C // C ∈ canonicalResidualComponents A x y L}) :
    IsLargePrime L
      (canonicalResidualCertificates hx hy C).prime :=
  (canonicalResidualCertificates hx hy C).prime_large

/-- Property (iii), left side: the selected prime divides `x+i`. -/
theorem canonicalResidualCertificates_prime_dvd_left
    {A x y L : ℕ}
    (hx : 1 ≤ x) (hy : 1 ≤ y)
    (C : {C // C ∈ canonicalResidualComponents A x y L}) :
    ((canonicalResidualCertificates hx hy C).prime : ℤ) ∣
      (x : ℤ) +
        channelVertexOffset
          (canonicalResidualCertificates hx hy C).left :=
  (canonicalResidualCertificates hx hy C)
    |>.prime_dvd_left_start_add_offset hx

/-- Property (iii), right side: the selected prime divides `y+j`. -/
theorem canonicalResidualCertificates_prime_dvd_right
    {A x y L : ℕ}
    (hx : 1 ≤ x) (hy : 1 ≤ y)
    (C : {C // C ∈ canonicalResidualComponents A x y L}) :
    ((canonicalResidualCertificates hx hy C).prime : ℤ) ∣
      (y : ℤ) +
        channelVertexOffset
          (canonicalResidualCertificates hx hy C).right :=
  (canonicalResidualCertificates hx hy C)
    |>.prime_dvd_right_start_add_offset hy

/-- Property (i): distinct residual components have distinct left offsets. -/
theorem canonicalResidualCertificates_leftOffset_injective
    {A x y L : ℕ}
    (hx : 1 ≤ x) (hy : 1 ≤ y) :
    Function.Injective
      (fun C :
          {C // C ∈ canonicalResidualComponents A x y L} ↦
        channelVertexOffset
          (canonicalResidualCertificates hx hy C).left) := by
  exact
    canonicalCertificates_leftOffset_injective
      hx hy
      (canonicalResidualComponents A x y L)
      (fun C hC ↦
        isNontrivialUnpinnedComponent_of_mem_canonicalResidualComponents
          hC)

/-- Property (i): distinct residual components have distinct right offsets. -/
theorem canonicalResidualCertificates_rightOffset_injective
    {A x y L : ℕ}
    (hx : 1 ≤ x) (hy : 1 ≤ y) :
    Function.Injective
      (fun C :
          {C // C ∈ canonicalResidualComponents A x y L} ↦
        channelVertexOffset
          (canonicalResidualCertificates hx hy C).right) := by
  exact
    canonicalCertificates_rightOffset_injective
      hx hy
      (canonicalResidualComponents A x y L)
      (fun C hC ↦
        isNontrivialUnpinnedComponent_of_mem_canonicalResidualComponents
          hC)

/-- Property (ii): distinct residual components select distinct primes. -/
theorem canonicalResidualCertificates_prime_injective
    {A x y L : ℕ}
    (hx : 1 ≤ x) (hy : 1 ≤ y) :
    Function.Injective
      (fun C :
          {C // C ∈ canonicalResidualComponents A x y L} ↦
        (canonicalResidualCertificates hx hy C).prime) := by
  exact
    canonicalCertificates_prime_injective
      hx hy
      (canonicalResidualComponents A x y L)
      (fun C hC ↦
        isNontrivialUnpinnedComponent_of_mem_canonicalResidualComponents
          hC)

/--
The canonical certificate index has exactly `c#` elements.  This is the
finite-family form of the manuscript's indexing `1 ≤ s ≤ c#`.
-/
theorem card_canonicalResidualCertificateIndex
    {A x y L : ℕ}
    (hx : 2 ≤ x) (hy : 2 ≤ y) :
    Fintype.card
        {C : (largePrimeGraph x y L).ConnectedComponent //
          C ∈ canonicalResidualComponents A x y L} =
      canonicalResidualComponentCount A x y L := by
  rw [Fintype.card_coe,
    card_canonicalResidualComponents hx hy]

/-- The finite set of primes selected by the canonical residual certificates. -/
noncomputable def canonicalResidualCertificatePrimes
    {A x y L : ℕ}
    (hx : 1 ≤ x) (hy : 1 ≤ y) :
    Finset ℕ :=
  canonicalCertificatePrimes
    hx hy
    (canonicalResidualComponents A x y L)
    (fun _C hC ↦
      isNontrivialUnpinnedComponent_of_mem_canonicalResidualComponents
        hC)

/-- Distinctness makes the selected-prime set have cardinality exactly `c#`. -/
theorem card_canonicalResidualCertificatePrimes
    {A x y L : ℕ}
    (hx : 2 ≤ x) (hy : 2 ≤ y) :
    (canonicalResidualCertificatePrimes
        (A := A) (L := L)
        (show 1 ≤ x by omega) (show 1 ≤ y by omega)).card =
      canonicalResidualComponentCount A x y L := by
  calc
    (canonicalResidualCertificatePrimes
        (A := A) (L := L)
        (show 1 ≤ x by omega) (show 1 ≤ y by omega)).card =
        (canonicalResidualComponents A x y L).card := by
      exact
        ResidualCertificates.card_canonicalCertificatePrimes
          (show 1 ≤ x by omega) (show 1 ≤ y by omega)
          (canonicalResidualComponents A x y L)
          (fun _C hC ↦
            isNontrivialUnpinnedComponent_of_mem_canonicalResidualComponents
              hC)
    _ = canonicalResidualComponentCount A x y L :=
      card_canonicalResidualComponents hx hy

/--
Property (iv): in the active canonical branch `m ≥ 2`, the selected
certificate cell is not aligned with the selected rational channel.
-/
theorem canonicalResidualCertificates_not_onChannel_of_choice
    {A x y L : ℕ}
    (hx : 1 ≤ x) (hy : 1 ≤ y)
    (c : ReducedCandidate
      x y (L + 1) ((L + 1) ^ A))
    (hchoice :
      canonicalReducedCandidate?
          x y (L + 1) ((L + 1) ^ A) =
        some c)
    (hm :
      2 ≤ channelUnitCount L c.1.1 c.1.2
        (pairChannelError x y c.1.1 c.1.2))
    (C : {C // C ∈ canonicalResidualComponents A x y L}) :
    ¬OnChannel c.1.1 c.1.2
      (pairChannelError x y c.1.1 c.1.2)
      (canonicalResidualCertificates hx hy C).offsetCell := by
  apply canonicalCertificates_not_onChannel_of_excluded
  intro cell hcell
  exact
    canonical_onChannel_component_not_mem_of_choice
      hx hy c hchoice hm cell hcell

/-- Algebraic nonvanishing form of property (iv). -/
theorem canonicalResidualCertificates_residualExpression_ne_of_choice
    {A x y L : ℕ}
    (hx : 1 ≤ x) (hy : 1 ≤ y)
    (c : ReducedCandidate
      x y (L + 1) ((L + 1) ^ A))
    (hchoice :
      canonicalReducedCandidate?
          x y (L + 1) ((L + 1) ^ A) =
        some c)
    (hm :
      2 ≤ channelUnitCount L c.1.1 c.1.2
        (pairChannelError x y c.1.1 c.1.2))
    (C : {C // C ∈ canonicalResidualComponents A x y L}) :
    pairChannelError x y c.1.1 c.1.2 +
          (c.1.2 : ℤ) *
            channelVertexOffset
              (canonicalResidualCertificates hx hy C).right -
          (c.1.1 : ℤ) *
            channelVertexOffset
              (canonicalResidualCertificates hx hy C).left ≠
        0 := by
  rw [← not_onChannel_iff_residualExpression_ne]
  exact
    canonicalResidualCertificates_not_onChannel_of_choice
      hx hy c hchoice hm C

/-! ## The canonical one-unit exceptional family -/

/--
For a selected canonical channel with exactly one unit, these are the
residual components meeting one of that unit's two distinguished
occurrences.
-/
noncomputable def canonicalOneUnitExceptionalComponents
    {A x y L : ℕ}
    (c : ReducedCandidate
      x y (L + 1) ((L + 1) ^ A))
    (_hchoice :
      canonicalReducedCandidate?
          x y (L + 1) ((L + 1) ^ A) =
        some c)
    (hm :
      channelUnitCount L c.1.1 c.1.2
        (pairChannelError x y c.1.1 c.1.2) = 1) :
    Finset (largePrimeGraph x y L).ConnectedComponent :=
  oneUnitExceptionalComponents
    (canonicalResidualComponents A x y L) hm

/-- Property (v), cardinal part: the exceptional canonical family has size at most two. -/
theorem card_canonicalOneUnitExceptionalComponents_le_two
    {A x y L : ℕ}
    (c : ReducedCandidate
      x y (L + 1) ((L + 1) ^ A))
    (hchoice :
      canonicalReducedCandidate?
          x y (L + 1) ((L + 1) ^ A) =
        some c)
    (hm :
      channelUnitCount L c.1.1 c.1.2
        (pairChannelError x y c.1.1 c.1.2) = 1) :
    (canonicalOneUnitExceptionalComponents
        c hchoice hm).card ≤ 2 := by
  exact
    card_oneUnitExceptionalComponents_le_two
      (canonicalResidualComponents A x y L) hm

/--
Property (v), support part: if a canonical residual certificate is exact
in the one-unit branch, its component belongs to the exceptional family.
-/
theorem canonicalResidualCertificate_mem_oneUnitExceptionalComponents_of_choice
    {A x y L : ℕ}
    (hx : 1 ≤ x) (hy : 1 ≤ y)
    (c : ReducedCandidate
      x y (L + 1) ((L + 1) ^ A))
    (hchoice :
      canonicalReducedCandidate?
          x y (L + 1) ((L + 1) ^ A) =
        some c)
    (hm :
      channelUnitCount L c.1.1 c.1.2
        (pairChannelError x y c.1.1 c.1.2) = 1)
    (C : {C // C ∈ canonicalResidualComponents A x y L})
    (hexact :
      OnChannel c.1.1 c.1.2
        (pairChannelError x y c.1.1 c.1.2)
        (canonicalResidualCertificates hx hy C).offsetCell) :
    C.1 ∈ canonicalOneUnitExceptionalComponents
      c hchoice hm := by
  exact
    canonicalCertificate_mem_oneUnitExceptionalComponents_of_onChannel
      hx hy
      (canonicalResidualComponents A x y L)
      (fun _C hC ↦
        isNontrivialUnpinnedComponent_of_mem_canonicalResidualComponents
          hC)
      hm C hexact

end

end CanonicalResidualComponents
end PaperC
