import PaperC.Combinatorics.CanonicalResidualComponents
import PaperC.Combinatorics.ResidualMasses
import PaperC.LinearAlgebra.CanonicalResidualQuotient
import PaperC.LinearAlgebra.NonalignedCoreRank
import Mathlib.LinearAlgebra.Matrix.ToLin

set_option maxHeartbeats 1200000

/-!
# Canonical exact rank for the nonaligned core

This module connects the abstract rank--nullity calculation of
`NonalignedCoreRank` to the canonical corrected objects already constructed
in Sections 5--6.

There are two genuinely concrete steps.

* We construct the corrected defective-vertex family by deleting, in the
  active rational channel, the defective vertices generated by exact units.
  Its cardinality is exactly `D#`.
* We sum that family with `canonicalResidualComponents`, whose cardinality is
  already exactly `c#`.  Thus the resulting binary coordinate space has
  exactly `D# + c#` coordinates, without a cardinality assumption.

The equations contributed by the remaining small-prime rows are represented
by an explicit finite `F₂` matrix.  The one interface not yet derived from
the arithmetic definitions is the linear equivalence identifying the
canonical residual quotient with the kernel of this matrix.  It is a field
of `CanonicalSmallRowPresentation`, not an axiom.  The audited existence
statement for the concrete arithmetic matrix lives in
`CanonicalSmallRows`; this file keeps only the data-level presentation.
Once such a presentation is supplied, the exact identity

`τ = D# + c# - k̃`

follows by rank--nullity.  This cleanly isolates the remaining internal
formalization debt: constructing the small-row matrix and proving that its
kernel presents the quotient.
-/

namespace PaperC
namespace CanonicalExactRank

open Affine
open Affine.CanonicalRationalCode
open Affine.RationalChannelCode
open CanonicalResidualComponents
open CanonicalResidualQuotient
open ExactUnitIsolation
open LargePrimeGraph
open LargePrimeGraphResolution
open LargePrimeOccurrences
open NonalignedCoreRank
open ResidualComponentCounts
open ResidualMasses

noncomputable section

/-! ## The corrected defective family -/

/--
Defective vertices generated by exact units of one explicit rational
channel.
-/
noncomputable def exactDefectiveVertices
    (x y L a b : ℕ) (h : ℤ) :
    Finset (Occurrence L) := by
  classical
  exact Finset.univ.image fun
    unit : DefectiveChannelUnit x y L a b h ↦
      Sum.inl unit.1.1.1

@[simp]
theorem mem_exactDefectiveVertices
    {x y L a b : ℕ} {h : ℤ} {v : Occurrence L} :
    v ∈ exactDefectiveVertices x y L a b h ↔
      ∃ unit : DefectiveChannelUnit x y L a b h,
        (Sum.inl unit.1.1.1 : Occurrence L) = v := by
  classical
  simp [exactDefectiveVertices]

/-- Every exact defective vertex belongs to the ambient defective family. -/
theorem exactDefectiveVertices_subset_defectiveVertices
    {x y L a b : ℕ} {h : ℤ} :
    exactDefectiveVertices x y L a b h ⊆
      defectiveVertices x y L := by
  classical
  intro v hv
  obtain ⟨unit, rfl⟩ :=
    mem_exactDefectiveVertices.mp hv
  exact mem_defectiveVertices.mpr unit.2

/--
Distinct exact units give distinct left vertices, so the concrete deleted
family has exactly `d` elements.
-/
theorem card_exactDefectiveVertices
    {x y L a b : ℕ} {h : ℤ}
    (hb : 0 < b) :
    (exactDefectiveVertices x y L a b h).card =
      defectiveExactUnitCount x y L a b h := by
  classical
  let f :
      DefectiveChannelUnit x y L a b h → Occurrence L :=
    fun unit ↦ Sum.inl unit.1.1.1
  have hf : Function.Injective f := by
    intro unit₁ unit₂ huv
    apply Subtype.ext
    exact
      channelUnit_left_injective hb
        (Sum.inl.inj huv)
  change (Finset.univ.image f).card =
    Fintype.card (DefectiveChannelUnit x y L a b h)
  rw [Finset.card_image_of_injective Finset.univ hf,
    Finset.card_univ]

/--
The explicit corrected defective family for one channel.  In the active
branch `m ≥ 2` the exact defective vertices are removed; otherwise the
ambient defective family is unchanged.
-/
noncomputable def correctedDefectiveVertices
    (x y L a b : ℕ) (h : ℤ) :
    Finset (Occurrence L) := by
  classical
  exact
    if 2 ≤ channelUnitCount L a b h then
      defectiveVertices x y L \
        exactDefectiveVertices x y L a b h
    else
      defectiveVertices x y L

/-- The explicit corrected family realizes the numerical count `D#`. -/
theorem card_correctedDefectiveVertices
    {x y L a b : ℕ} {h : ℤ}
    (hb : 0 < b) :
    (correctedDefectiveVertices x y L a b h).card =
      correctedDefectCount x y L a b h := by
  classical
  by_cases hm : 2 ≤ channelUnitCount L a b h
  · have hsubset :
        exactDefectiveVertices x y L a b h ⊆
          defectiveVertices x y L :=
      exactDefectiveVertices_subset_defectiveVertices
    simp only [correctedDefectiveVertices, correctedDefectCount,
      if_pos hm]
    rw [Finset.card_sdiff_of_subset hsubset,
      card_exactDefectiveVertices hb]
    rfl
  · simp [correctedDefectiveVertices, correctedDefectCount, hm,
      defectiveVertexCount]

/--
Canonical corrected defective vertices, using the same optional canonical
channel as `canonicalCorrectedDefectCount`.
-/
noncomputable def canonicalCorrectedDefectiveVertices
    (A x y L : ℕ) :
    Finset (Occurrence L) :=
  match canonicalReducedCandidate?
      x y (L + 1) ((L + 1) ^ A) with
  | none => defectiveVertices x y L
  | some c =>
      correctedDefectiveVertices
        x y L c.1.1 c.1.2
        (pairChannelError x y c.1.1 c.1.2)

/-- The canonical corrected defective family has cardinality exactly `D#`. -/
theorem card_canonicalCorrectedDefectiveVertices
    (A x y L : ℕ) :
    (canonicalCorrectedDefectiveVertices A x y L).card =
      canonicalCorrectedDefectCount A x y L := by
  classical
  generalize hchoice :
      canonicalReducedCandidate?
        x y (L + 1) ((L + 1) ^ A) = choice
  cases choice with
  | none =>
      simp [canonicalCorrectedDefectiveVertices,
        canonicalCorrectedDefectCount, hchoice,
        defectiveVertexCount]
  | some c =>
      have hcard :=
        card_correctedDefectiveVertices
          (x := x) (y := y) (L := L)
          (a := c.1.1) (b := c.1.2)
          (h := pairChannelError x y c.1.1 c.1.2)
          (candidate_snd_pos c)
      simpa [canonicalCorrectedDefectiveVertices,
        canonicalCorrectedDefectCount, hchoice]
        using hcard

/-! ## Canonical coordinates and small-row matrices -/

/--
The literal coordinate index for the nonaligned core: a corrected defective
vertex or a canonical residual nontrivial component.
-/
abbrev CanonicalCoreCoordinate
    (A x y L : ℕ) :=
  {v : Occurrence L //
      v ∈ canonicalCorrectedDefectiveVertices A x y L} ⊕
    {C : (largePrimeGraph x y L).ConnectedComponent //
      C ∈ canonicalResidualComponents A x y L}

/-- The canonical coordinate family has exactly `D# + c#` elements. -/
theorem card_canonicalCoreCoordinate
    {A x y L : ℕ}
    (hx : 2 ≤ x) (hy : 2 ≤ y) :
    Fintype.card (CanonicalCoreCoordinate A x y L) =
      canonicalCorrectedDefectCount A x y L +
        canonicalResidualComponentCount A x y L := by
  rw [Fintype.card_sum, Fintype.card_coe, Fintype.card_coe,
    card_canonicalCorrectedDefectiveVertices,
    card_canonicalResidualComponents hx hy]

/--
An explicit finite matrix of the remaining small-prime equations.
Rows are indexed by `Fin rowCount`; columns are the canonical `D# + c#`
coordinates.
-/
abbrev CanonicalSmallRowMatrix
    (rowCount A x y L : ℕ) :=
  Matrix (Fin rowCount) (CanonicalCoreCoordinate A x y L) F₂

/-- The manuscript's `k̃`, realized as the rank of the small-row matrix. -/
noncomputable def canonicalSmallRowRank
    {rowCount A x y L : ℕ}
    (matrix : CanonicalSmallRowMatrix rowCount A x y L) : ℕ :=
  kTilde matrix.mulVecLin

/--
Exact rank--nullity on the canonical coordinates.  Unlike
`NonalignedCoreRank.lemma_nine_ten_exact_rank`, this theorem needs no
cardinality hypothesis: both coordinate families are concrete finsets.
-/
theorem finrank_canonicalSmallRowKernel
    {rowCount A x y L : ℕ}
    (hx : 2 ≤ x) (hy : 2 ≤ y)
    (matrix : CanonicalSmallRowMatrix rowCount A x y L) :
    Module.finrank F₂ (LinearMap.ker matrix.mulVecLin) =
      canonicalCorrectedDefectCount A x y L +
          canonicalResidualComponentCount A x y L -
        canonicalSmallRowRank matrix := by
  rw [finrank_componentKernel_eq_card_sub_kTilde,
    card_canonicalCoreCoordinate hx hy]
  rfl

/-- The small-row rank cannot exceed the number `D# + c#` of columns. -/
theorem canonicalSmallRowRank_le_corrected_add_components
    {rowCount A x y L : ℕ}
    (hx : 2 ≤ x) (hy : 2 ≤ y)
    (matrix : CanonicalSmallRowMatrix rowCount A x y L) :
    canonicalSmallRowRank matrix ≤
      canonicalCorrectedDefectCount A x y L +
        canonicalResidualComponentCount A x y L := by
  have hrankNullity :=
    LinearMap.finrank_range_add_finrank_ker matrix.mulVecLin
  rw [Module.finrank_pi,
    card_canonicalCoreCoordinate hx hy] at hrankNullity
  unfold canonicalSmallRowRank kTilde
  omega

/-! ## Identification with the canonical residual quotient -/

/--
A finite small-row presentation of the canonical residual quotient.

The matrix is fully explicit.  The equivalence field is the precise
remaining boundary: future work must construct it from the small-prime
valuation rows and verify that those rows cut out exactly the residual
quotient.
-/
structure CanonicalSmallRowPresentation
    (M A x y L : ℕ) (hx : 2 ≤ x) (hy : 2 ≤ y) where
  rowCount : ℕ
  matrix : CanonicalSmallRowMatrix rowCount A x y L
  quotientEquivKernel :
    ResidualQuotient M A x y L hx hy ≃ₗ[F₂]
      LinearMap.ker matrix.mulVecLin

/-- `k̃` attached to a concrete canonical small-row presentation. -/
noncomputable def CanonicalSmallRowPresentation.kTilde
    {M A x y L : ℕ} {hx : 2 ≤ x} {hy : 2 ≤ y}
    (presentation :
      CanonicalSmallRowPresentation M A x y L hx hy) : ℕ :=
  canonicalSmallRowRank presentation.matrix

/--
Lemma 9.10 for the literal residual quotient: every supplied canonical
small-row presentation satisfies `τ = D# + c# - k̃`.
-/
theorem residualTau_eq_corrected_add_components_sub_kTilde
    {M A x y L : ℕ}
    (hx : 2 ≤ x) (hy : 2 ≤ y)
    (presentation :
      CanonicalSmallRowPresentation M A x y L hx hy) :
    residualTau M A x y L hx hy =
      canonicalCorrectedDefectCount A x y L +
          canonicalResidualComponentCount A x y L -
        presentation.kTilde := by
  calc
    residualTau M A x y L hx hy =
        Module.finrank F₂
          (ResidualQuotient M A x y L hx hy) :=
      residualTau_eq_finrank_residualQuotient
        M A x y L hx hy
    _ =
        Module.finrank F₂
          (LinearMap.ker presentation.matrix.mulVecLin) :=
      LinearEquiv.finrank_eq presentation.quotientEquivKernel
    _ =
        canonicalCorrectedDefectCount A x y L +
            canonicalResidualComponentCount A x y L -
          canonicalSmallRowRank presentation.matrix :=
      finrank_canonicalSmallRowKernel
        hx hy presentation.matrix
    _ =
        canonicalCorrectedDefectCount A x y L +
            canonicalResidualComponentCount A x y L -
          presentation.kTilde :=
      rfl

/--
Equivalent non-truncated form of the quotient identity:
`τ + k̃ = D# + c#`.
-/
theorem residualTau_add_kTilde_eq_corrected_add_components
    {M A x y L : ℕ}
    (hx : 2 ≤ x) (hy : 2 ≤ y)
    (presentation :
      CanonicalSmallRowPresentation M A x y L hx hy) :
    residualTau M A x y L hx hy +
        presentation.kTilde =
      canonicalCorrectedDefectCount A x y L +
        canonicalResidualComponentCount A x y L := by
  rw [residualTau_eq_corrected_add_components_sub_kTilde
    hx hy presentation]
  exact Nat.sub_add_cancel
    (canonicalSmallRowRank_le_corrected_add_components
      hx hy presentation.matrix)

/--
Pair-level form of Lemma 9.10, stated directly using `pairTau`.
-/
theorem pairTau_eq_corrected_add_components_sub_kTilde
    {N A L : ℕ}
    (hN : 2 ≤ N)
    (pair : SeparatedDyadicPair N L)
    (presentation :
      CanonicalSmallRowPresentation
        (dyadicCutoff N L) A pair.1.1 pair.1.2 L
        (pair_coordinates_two_le hN pair).1
        (pair_coordinates_two_le hN pair).2) :
    pairTau A hN pair =
      canonicalCorrectedDefectCount
            A pair.1.1 pair.1.2 L +
          canonicalResidualComponentCount
            A pair.1.1 pair.1.2 L -
        presentation.kTilde := by
  unfold pairTau
  exact
    residualTau_eq_corrected_add_components_sub_kTilde
      (pair_coordinates_two_le hN pair).1
      (pair_coordinates_two_le hN pair).2
      presentation

/-- Pair-level additive form `τ + k̃ = D# + c#`. -/
theorem pairTau_add_kTilde_eq_corrected_add_components
    {N A L : ℕ}
    (hN : 2 ≤ N)
    (pair : SeparatedDyadicPair N L)
    (presentation :
      CanonicalSmallRowPresentation
        (dyadicCutoff N L) A pair.1.1 pair.1.2 L
        (pair_coordinates_two_le hN pair).1
        (pair_coordinates_two_le hN pair).2) :
    pairTau A hN pair + presentation.kTilde =
      canonicalCorrectedDefectCount
            A pair.1.1 pair.1.2 L +
        canonicalResidualComponentCount
          A pair.1.1 pair.1.2 L := by
  unfold pairTau
  exact
    residualTau_add_kTilde_eq_corrected_add_components
      (pair_coordinates_two_le hN pair).1
      (pair_coordinates_two_le hN pair).2
      presentation

end

end CanonicalExactRank
end PaperC
