import Mathlib.Data.Multiset.Interval
import Mathlib.NumberTheory.ArithmeticFunction
import Mathlib.NumberTheory.NumberField.Basic
import Mathlib.NumberTheory.RamificationInertia.Galois
import Mathlib.RingTheory.Coprime.Lemmas
import Mathlib.RingTheory.DedekindDomain.Ideal
import Mathlib.RingTheory.Int.Basic
import Mathlib.RingTheory.UniqueFactorizationDomain.Finite

/-!
# Divisors of principal integer ideals in quadratic number fields

This module proves the ideal-divisor estimate used in the ideal-theoretic
proof of generalized Pell:

`#{I : Ideal (𝓞 K) | I ∣ (M)} ≤ τ(|M|)²`

for every quadratic number field `K` and every nonzero integer `M`.

The proof has four parts:

* divisors of a nonzero ideal are identified with submultisets of its
  normalized prime factorization;
* factor-count products are assembled multiplicatively over coprime
  rational primes;
* the quadratic identity `r * e * f = 2` bounds every local factor by
  `(a + 1)²`;
* the ordinary factorization of `|M|` identifies the resulting product with
  `τ(|M|)²`.
-/

open scoped NumberField Classical

namespace PaperC
namespace QuadraticIdealDivisors

noncomputable section

/-! ## Principal integer ideals -/

/-- Mapping `(M)` from `ℤ` to `𝓞 K` gives the principal ideal generated by
the integer cast. -/
theorem map_span_int_eq_span_intCast
    (K : Type*) [Field K] [NumberField K] (M : ℤ) :
    (Ideal.span ({M} : Set ℤ)).map (algebraMap ℤ (𝓞 K)) =
      Ideal.span ({(M : 𝓞 K)} : Set (𝓞 K)) := by
  rw [Ideal.map_span]
  simp

/-- The sign of an integer does not change its principal ideal in `𝓞 K`. -/
theorem span_intCast_eq_span_natAbs
    (K : Type*) [Field K] [NumberField K] (M : ℤ) :
    Ideal.span ({(M : 𝓞 K)} : Set (𝓞 K)) =
      Ideal.span ({(M.natAbs : 𝓞 K)} : Set (𝓞 K)) := by
  rw [Ideal.span_singleton_eq_span_singleton]
  convert (Int.associated_natAbs M).map
    (algebraMap ℤ (𝓞 K)) using 1
  exact (map_natCast (algebraMap ℤ (𝓞 K)) M.natAbs).symm

/-- The ideal `(p)` of `ℤ` is maximal when `p` is a natural prime. -/
theorem span_natPrime_isMaximal {p : ℕ} (hp : p.Prime) :
    (Ideal.span ({(p : ℤ)} : Set ℤ)).IsMaximal := by
  have hpZ : Prime (p : ℤ) := by
    rw [Int.prime_iff_natAbs_prime]
    simpa using hp
  have hI0 :
      Ideal.span ({(p : ℤ)} : Set ℤ) ≠ (⊥ : Ideal ℤ) :=
    mt Ideal.span_singleton_eq_bot.mp hpZ.ne_zero
  apply Ring.DimensionLEOne.maximalOfPrime hI0
  exact (Ideal.span_singleton_prime hpZ.ne_zero).mpr hpZ

theorem span_natPrime_ne_bot {p : ℕ} (hp : p.Prime) :
    Ideal.span ({(p : ℤ)} : Set ℤ) ≠ (⊥ : Ideal ℤ) :=
  mt Ideal.span_singleton_eq_bot.mp
    (show (p : ℤ) ≠ 0 by exact_mod_cast hp.ne_zero)

/-- Assemble a principal ideal from the ordinary prime factorization of a
nonzero natural number. -/
theorem span_natCast_eq_prod_primeFactors
    {B : Type*} [CommRing B] [IsDomain B] [CharZero B]
    (n : ℕ) (hn : n ≠ 0) :
    Ideal.span ({(n : B)} : Set B) =
      ∏ p ∈ n.primeFactors,
        (Ideal.span ({(p : B)} : Set B)) ^ n.factorization p := by
  simp_rw [Ideal.span_singleton_pow]
  rw [Ideal.prod_span_singleton]
  congr 2
  norm_cast
  rw [← Nat.prod_factorization_eq_prod_primeFactors]
  exact_mod_cast (Nat.factorization_prod_pow_eq_self hn).symm

/-! ## Exact divisor cardinality in a Dedekind domain -/

/-- Divisors of a nonzero ideal are exactly the submultisets of its
normalized prime factorization.  Ideals have unique units, so the usual
correspondence up to associates is an actual equivalence. -/
def idealDivisorFactorsEquiv
    {R : Type*} [CommRing R] [IsDedekindDomain R]
    (J : Ideal R) (hJ : J ≠ ⊥) :
    {I : Ideal R // I ∣ J} ≃
      {s : Multiset (Ideal R) //
        s ≤ UniqueFactorizationMonoid.normalizedFactors J} where
  toFun I := by
    have hI : (I : Ideal R) ≠ ⊥ := by
      intro h
      have hbot : (⊥ : Ideal R) ∣ J := h ▸ I.property
      exact hJ (zero_dvd_iff.mp hbot)
    exact
      ⟨UniqueFactorizationMonoid.normalizedFactors I,
        (UniqueFactorizationMonoid.dvd_iff_normalizedFactors_le_normalizedFactors
          hI hJ).mp I.property⟩
  invFun s := by
    refine ⟨s.1.prod, ?_⟩
    simpa only [prod_normalizedFactors_eq_self hJ] using
      Multiset.prod_dvd_prod_of_le s.2
  left_inv I := by
    apply Subtype.ext
    exact prod_normalizedFactors_eq_self
      (by
        intro h
        have hbot : (⊥ : Ideal R) ∣ J := h ▸ I.property
        exact hJ (zero_dvd_iff.mp hbot))
  right_inv s := by
    apply Subtype.ext
    apply UniqueFactorizationMonoid.normalizedFactors_prod_of_prime
    intro P hP
    exact UniqueFactorizationMonoid.prime_of_normalized_factor P
      (Multiset.mem_of_le s.2 hP)

/-- Exact divisor-cardinality formula for a nonzero ideal in a Dedekind
domain. -/
theorem natCard_idealDivisors_eq_prod_factorCounts
    {R : Type*} [CommRing R] [IsDedekindDomain R]
    [DecidableEq (Ideal R)]
    (J : Ideal R) (hJ : J ≠ ⊥) :
    Nat.card {I : Ideal R // I ∣ J} =
      ∏ P ∈ (UniqueFactorizationMonoid.normalizedFactors J).toFinset,
        ((UniqueFactorizationMonoid.normalizedFactors J).count P + 1) := by
  classical
  let t := UniqueFactorizationMonoid.normalizedFactors J
  calc
    Nat.card {I : Ideal R // I ∣ J} =
        Nat.card {s : Multiset (Ideal R) // s ≤ t} :=
      Nat.card_congr (idealDivisorFactorsEquiv J hJ)
    _ = (Finset.Iic t).card := by
      change Nat.card (Set.Iic t) = _
      rw [Nat.card_eq_fintype_card, Fintype.card_Iic]
    _ = ∏ P ∈ t.toFinset, (t.count P + 1) :=
      Multiset.card_Iic t

/-! ## Coprime assembly of factor-count products -/

/-- The product occurring in the exact divisor-cardinality formula. -/
noncomputable def factorCountProduct
    {R : Type*} [CancelCommMonoidWithZero R]
    [NormalizationMonoid R] [UniqueFactorizationMonoid R]
    (x : R) : ℕ :=
  ∏ p ∈ (UniqueFactorizationMonoid.normalizedFactors x).toFinset,
    ((UniqueFactorizationMonoid.normalizedFactors x).count p + 1)

/-- The normalized factors of coprime elements are disjoint.  This
semiring-level form applies to the multiplicative semiring of ideals. -/
theorem disjoint_normalizedFactors_of_isCoprime
    {R : Type*} [CommSemiring R] [IsDomain R]
    [NormalizationMonoid R] [UniqueFactorizationMonoid R]
    {x y : R} (hxy : IsCoprime x y) :
    Disjoint
      (UniqueFactorizationMonoid.normalizedFactors x)
      (UniqueFactorizationMonoid.normalizedFactors y) := by
  rw [Multiset.disjoint_left]
  intro p hpx hpy
  have hpxd := UniqueFactorizationMonoid.dvd_of_mem_normalizedFactors hpx
  have hpyd := UniqueFactorizationMonoid.dvd_of_mem_normalizedFactors hpy
  have hp := UniqueFactorizationMonoid.prime_of_normalized_factor p hpx
  exact hp.not_unit (hxy.isUnit_of_dvd' hpxd hpyd)

/-- `factorCountProduct` is multiplicative on coprime nonzero elements. -/
theorem factorCountProduct_mul_of_isCoprime
    {R : Type*} [CommSemiring R] [IsDomain R]
    [NormalizationMonoid R] [UniqueFactorizationMonoid R]
    {x y : R} (hx : x ≠ 0) (hy : y ≠ 0) (hxy : IsCoprime x y) :
    factorCountProduct (x * y) =
      factorCountProduct x * factorCountProduct y := by
  classical
  unfold factorCountProduct
  let sx := UniqueFactorizationMonoid.normalizedFactors x
  let sy := UniqueFactorizationMonoid.normalizedFactors y
  have hd : Disjoint sx sy :=
    disjoint_normalizedFactors_of_isCoprime hxy
  have hdf : Disjoint sx.toFinset sy.toFinset :=
    Multiset.disjoint_toFinset.mpr hd
  rw [UniqueFactorizationMonoid.normalizedFactors_mul hx hy,
    Multiset.toFinset_add, Finset.prod_union hdf]
  congr 1
  · apply Finset.prod_congr rfl
    intro p hp
    rw [Multiset.count_add,
      Multiset.count_eq_zero.mpr
        ((Multiset.disjoint_left.mp hd)
          (Multiset.mem_toFinset.mp hp))]
  · apply Finset.prod_congr rfl
    intro p hp
    rw [Multiset.count_add,
      Multiset.count_eq_zero.mpr
        ((Multiset.disjoint_right.mp hd)
          (Multiset.mem_toFinset.mp hp))]
    omega

/-- Finite pairwise-coprime assembly of factor-count products. -/
theorem factorCountProduct_finset_prod_of_pairwise
    {R ι : Type*} [CommSemiring R] [IsDomain R]
    [NormalizationMonoid R] [UniqueFactorizationMonoid R]
    (s : Finset ι) (g : ι → R)
    (hg0 : ∀ i ∈ s, g i ≠ 0)
    (hcop : ∀ i ∈ s, ∀ j ∈ s, i ≠ j → IsCoprime (g i) (g j)) :
    factorCountProduct (∏ i ∈ s, g i) =
      ∏ i ∈ s, factorCountProduct (g i) := by
  classical
  induction s using Finset.induction_on with
  | empty =>
      simp [factorCountProduct]
  | @insert a s ha ih =>
      have hga : g a ≠ 0 := hg0 a (Finset.mem_insert_self a s)
      have hgs : ∀ i ∈ s, g i ≠ 0 :=
        fun i hi => hg0 i (Finset.mem_insert_of_mem hi)
      have hprod0 : (∏ i ∈ s, g i) ≠ 0 :=
        Finset.prod_ne_zero_iff.mpr hgs
      have hacop : IsCoprime (g a) (∏ i ∈ s, g i) := by
        apply IsCoprime.prod_right
        intro i hi
        exact hcop a (Finset.mem_insert_self a s)
          i (Finset.mem_insert_of_mem hi)
          (Ne.symm (ne_of_mem_of_not_mem hi ha))
      rw [Finset.prod_insert ha, Finset.prod_insert ha,
        factorCountProduct_mul_of_isCoprime hga hprod0 hacop]
      rw [ih hgs]
      intro i hi j hj hij
      exact hcop i (Finset.mem_insert_of_mem hi)
        j (Finset.mem_insert_of_mem hj) hij

/-! ## The local quadratic estimate -/

/-- The elementary numerical form of the local quadratic splitting
estimate.  Here `r`, `e`, and `f` are the number of primes, ramification
index, and inertia degree above a rational prime. -/
theorem local_quadratic_factor_bound
    (a r e f : ℕ) (hr : 1 ≤ r) (hfund : r * (e * f) = 2) :
    (a * e + 1) ^ r ≤ (a + 1) ^ 2 := by
  have hr2 : r ≤ 2 := by
    apply Nat.le_of_dvd (by decide)
    exact ⟨e * f, hfund.symm⟩
  interval_cases r
  · have he : e ≤ 2 := by
      apply Nat.le_of_dvd (by decide)
      exact ⟨f, by simpa using hfund.symm⟩
    simp only [pow_one]
    nlinarith
  · have hef : e * f = 1 := by omega
    have he : e = 1 := Nat.eq_one_of_mul_eq_one_right hef
    simp [he]

/-- Local factor bound for a power of a rational maximal ideal extended to
a quadratic number field. -/
theorem factorCountProduct_mappedPrimePower_le
    (K : Type*) [Field K] [NumberField K]
    [Algebra.IsQuadraticExtension ℚ K]
    (p : Ideal ℤ) (hp : p ≠ ⊥) [p.IsMaximal]
    (a : ℕ) (ha : a ≠ 0) :
    factorCountProduct
        ((Ideal.map (algebraMap ℤ (𝓞 K)) p) ^ a) ≤
      (a + 1) ^ 2 := by
  classical
  letI : IsGalois ℚ K := inferInstance
  let J : Ideal (𝓞 K) := Ideal.map (algebraMap ℤ (𝓞 K)) p
  let t : Multiset (Ideal (𝓞 K)) :=
    UniqueFactorizationMonoid.normalizedFactors J
  let r : ℕ := (Ideal.primesOver p (𝓞 K)).ncard
  let e : ℕ := Ideal.ramificationIdxIn p (𝓞 K)
  let f : ℕ := Ideal.inertiaDegIn p (𝓞 K)
  have hJ : J ≠ ⊥ := Ideal.map_ne_bot_of_ne_bot hp
  have ht_support : t.toFinset = primesOverFinset p (𝓞 K) := by
    simp only [t, J, primesOverFinset,
      UniqueFactorizationMonoid.factors_eq_normalizedFactors]
  have hcount (P : Ideal (𝓞 K)) (hP : P ∈ t.toFinset) :
      t.count P = e := by
    have hPover : P ∈ Ideal.primesOver p (𝓞 K) := by
      rw [← coe_primesOverFinset hp (𝓞 K)]
      simpa only [Finset.mem_coe, ← ht_support] using hP
    letI : P.IsPrime := hPover.1
    letI : P.LiesOver p := hPover.2
    have hPmem : P ∈ t := Multiset.mem_toFinset.mp hP
    have hP0 : P ≠ ⊥ := by
      intro hPbot
      have hbotmem : (⊥ : Ideal (𝓞 K)) ∈ t := by
        simpa only [hPbot] using hPmem
      exact UniqueFactorizationMonoid.zero_not_mem_normalizedFactors J
        (by simpa only [Ideal.zero_eq_bot] using hbotmem)
    calc
      t.count P =
          Ideal.ramificationIdx (algebraMap ℤ (𝓞 K)) p P :=
        (Ideal.IsDedekindDomain.ramificationIdx_eq_normalizedFactors_count
          hJ hPover.1 hP0).symm
      _ = e :=
        (Ideal.ramificationIdxIn_eq_ramificationIdx p P ℚ K).symm
  have hcard : t.toFinset.card = r := by
    rw [ht_support, ← Set.ncard_coe_Finset,
      coe_primesOverFinset hp (𝓞 K)]
  have hr : 1 ≤ r :=
    one_le_primesOver_ncard p (𝓞 K)
  have hfund : r * (e * f) = 2 := by
    simpa only [r, e, f, Algebra.IsQuadraticExtension.finrank_eq_two] using
      (Ideal.ncard_primesOver_mul_ramificationIdxIn_mul_inertiaDegIn
        hp (𝓞 K) ℚ K)
  unfold factorCountProduct
  rw [UniqueFactorizationMonoid.normalizedFactors_pow]
  change
    (∏ P ∈ (a • t).toFinset, ((a • t).count P + 1)) ≤
      (a + 1) ^ 2
  rw [Multiset.toFinset_nsmul t a ha]
  simp_rw [Multiset.count_nsmul]
  calc
    (∏ P ∈ t.toFinset, (a * t.count P + 1)) =
        (a * e + 1) ^ r := by
      rw [← hcard, ← Finset.prod_const]
      apply Finset.prod_congr rfl
      intro P hP
      rw [hcount P hP]
    _ ≤ (a + 1) ^ 2 :=
      local_quadratic_factor_bound a r e f hr hfund

/-- Local factor bound in the natural-prime form used below. -/
theorem factorCountProduct_span_natPrime_pow_le
    (K : Type*) [Field K] [NumberField K]
    [Algebra.IsQuadraticExtension ℚ K]
    {p : ℕ} (hp : p.Prime)
    (a : ℕ) (ha : a ≠ 0) :
    factorCountProduct
        ((Ideal.span ({(p : 𝓞 K)} : Set (𝓞 K))) ^ a) ≤
      (a + 1) ^ 2 := by
  classical
  let pI : Ideal ℤ := Ideal.span ({(p : ℤ)} : Set ℤ)
  letI : pI.IsMaximal := span_natPrime_isMaximal hp
  have hlocal :=
    factorCountProduct_mappedPrimePower_le K pI
      (span_natPrime_ne_bot hp) a ha
  simpa only [pI, map_span_int_eq_span_intCast,
    Int.cast_natCast] using hlocal

/-! ## Global assembly and the `τ²` bound -/

/-- The rational-prime-power ideal occurring in the factorization of
`(n)`. -/
noncomputable def rationalPrimePowerIdeal
    (K : Type*) [Field K] [NumberField K] (n p : ℕ) :
    Ideal (𝓞 K) :=
  (Ideal.span ({(p : 𝓞 K)} : Set (𝓞 K))) ^ n.factorization p

theorem factorization_ne_zero_of_mem_primeFactors
    {n p : ℕ} (hp : p ∈ n.primeFactors) :
    n.factorization p ≠ 0 := by
  have hsupp : p ∈ n.factorization.support := by
    rwa [Nat.support_factorization]
  exact Finsupp.mem_support_iff.mp hsupp

theorem rationalPrimePowerIdeal_ne_bot
    (K : Type*) [Field K] [NumberField K]
    {n p : ℕ} (hp : p ∈ n.primeFactors) :
    rationalPrimePowerIdeal K n p ≠ ⊥ := by
  apply pow_ne_zero
  exact mt Ideal.span_singleton_eq_bot.mp
    (Nat.cast_ne_zero.mpr
      (Nat.prime_of_mem_primeFactors hp).ne_zero)

theorem rationalPrimePowerIdeal_isCoprime
    (K : Type*) [Field K] [NumberField K]
    {n p q : ℕ}
    (hp : p ∈ n.primeFactors) (hq : q ∈ n.primeFactors)
    (hpq : p ≠ q) :
    IsCoprime (rationalPrimePowerIdeal K n p)
      (rationalPrimePowerIdeal K n q) := by
  have hbase : IsCoprime
      (Ideal.span ({(p : 𝓞 K)} : Set (𝓞 K)))
      (Ideal.span ({(q : 𝓞 K)} : Set (𝓞 K))) := by
    rw [Ideal.isCoprime_span_singleton_iff]
    exact
      ((Nat.coprime_primes
        (Nat.prime_of_mem_primeFactors hp)
        (Nat.prime_of_mem_primeFactors hq)).mpr hpq).cast
  exact hbase.pow

theorem factorCountProduct_primeFactors_assembly
    (K : Type*) [Field K] [NumberField K] (n : ℕ) :
    factorCountProduct
        (∏ p ∈ n.primeFactors, rationalPrimePowerIdeal K n p) =
      ∏ p ∈ n.primeFactors,
        factorCountProduct (rationalPrimePowerIdeal K n p) := by
  apply
    factorCountProduct_finset_prod_of_pairwise
      (R := Ideal (𝓞 K)) (ι := ℕ)
      n.primeFactors (rationalPrimePowerIdeal K n)
  · intro p hp
    exact rationalPrimePowerIdeal_ne_bot K hp
  · intro p hp q hq hpq
    exact rationalPrimePowerIdeal_isCoprime K hp hq hpq

theorem span_natCast_eq_prod_rationalPrimePowerIdeal
    (K : Type*) [Field K] [NumberField K]
    (n : ℕ) (hn : n ≠ 0) :
    Ideal.span ({(n : 𝓞 K)} : Set (𝓞 K)) =
      ∏ p ∈ n.primeFactors, rationalPrimePowerIdeal K n p := by
  simpa only [rationalPrimePowerIdeal] using
    (span_natCast_eq_prod_primeFactors (B := 𝓞 K) n hn)

theorem factorCountProduct_rationalPrimePowerIdeal_le
    (K : Type*) [Field K] [NumberField K]
    [Algebra.IsQuadraticExtension ℚ K]
    {n p : ℕ} (hp : p ∈ n.primeFactors) :
    factorCountProduct (rationalPrimePowerIdeal K n p) ≤
      (n.factorization p + 1) ^ 2 :=
  factorCountProduct_span_natPrime_pow_le K
    (Nat.prime_of_mem_primeFactors hp)
    (n.factorization p)
    (factorization_ne_zero_of_mem_primeFactors hp)

theorem prod_factorCountProduct_rationalPrimePowerIdeal_le
    (K : Type*) [Field K] [NumberField K]
    [Algebra.IsQuadraticExtension ℚ K]
    (n : ℕ) :
    (∏ p ∈ n.primeFactors,
        factorCountProduct (rationalPrimePowerIdeal K n p)) ≤
      ∏ p ∈ n.primeFactors,
        (n.factorization p + 1) ^ 2 := by
  apply Finset.prod_le_prod
  · intro p hp
    omega
  intro p hp
  exact factorCountProduct_rationalPrimePowerIdeal_le K hp

/-- The factor-count product for `(n)` is bounded by `τ(n)²`. -/
theorem factorCountProduct_span_natCast_le_tauSq
    (K : Type*) [Field K] [NumberField K]
    [Algebra.IsQuadraticExtension ℚ K]
    (n : ℕ) (hn : n ≠ 0) :
    factorCountProduct
        (Ideal.span ({(n : 𝓞 K)} : Set (𝓞 K))) ≤
      n.divisors.card ^ 2 := by
  calc
    factorCountProduct
        (Ideal.span ({(n : 𝓞 K)} : Set (𝓞 K))) =
        factorCountProduct
          (∏ p ∈ n.primeFactors,
            rationalPrimePowerIdeal K n p) := by
      rw [span_natCast_eq_prod_rationalPrimePowerIdeal K n hn]
    _ = ∏ p ∈ n.primeFactors,
        factorCountProduct (rationalPrimePowerIdeal K n p) :=
      factorCountProduct_primeFactors_assembly K n
    _ ≤ ∏ p ∈ n.primeFactors,
        (n.factorization p + 1) ^ 2 :=
      prod_factorCountProduct_rationalPrimePowerIdeal_le K n
    _ = (∏ p ∈ n.primeFactors,
        (n.factorization p + 1)) ^ 2 := by
      rw [Finset.prod_pow]
    _ = n.divisors.card ^ 2 := by
      rw [Nat.card_divisors hn]

/-- Natural-number form of the ideal-divisor bound. -/
theorem natCard_idealDivisors_span_natCast_le_tauSq
    (K : Type*) [Field K] [NumberField K]
    [Algebra.IsQuadraticExtension ℚ K]
    (n : ℕ) (hn : n ≠ 0) :
    Nat.card
        {I : Ideal (𝓞 K) //
          I ∣ Ideal.span ({(n : 𝓞 K)} : Set (𝓞 K))} ≤
      n.divisors.card ^ 2 := by
  classical
  let J : Ideal (𝓞 K) :=
    Ideal.span ({(n : 𝓞 K)} : Set (𝓞 K))
  have hJ : J ≠ ⊥ :=
    mt Ideal.span_singleton_eq_bot.mp
      (Nat.cast_ne_zero.mpr hn)
  calc
    Nat.card {I : Ideal (𝓞 K) // I ∣ J} =
        factorCountProduct J := by
      simpa only [factorCountProduct] using
        (natCard_idealDivisors_eq_prod_factorCounts J hJ)
    _ ≤ n.divisors.card ^ 2 :=
      factorCountProduct_span_natCast_le_tauSq K n hn

/--
For a quadratic number field `K` and nonzero integer `M`, the number of
integral ideals dividing `(M)` is at most `τ(|M|)²`.
-/
theorem quadraticIdealDivisorTauSq
    (K : Type*) [Field K] [NumberField K]
    [Algebra.IsQuadraticExtension ℚ K]
    (M : ℤ) (hM : M ≠ 0) :
    Nat.card
        {I : Ideal (𝓞 K) //
          I ∣ Ideal.span ({(M : 𝓞 K)} : Set (𝓞 K))} ≤
      M.natAbs.divisors.card ^ 2 := by
  have hn : M.natAbs ≠ 0 := Int.natAbs_ne_zero.mpr hM
  simpa only [span_intCast_eq_span_natAbs] using
    (natCard_idealDivisors_span_natCast_le_tauSq K M.natAbs hn)

end

end QuadraticIdealDivisors
end PaperC
